-- Content batch 1: 52 facts across 12 region x era themes, so each
-- theme has about five facts with the demo facts of 001.
-- Same rerunnable upsert format as 001_demo_facts.sql (keyed on slug).
-- source_url is the French Wikipedia article each text was written from; every
-- year was cross-checked against it. Images are the article's lead image, with
-- author and license read from the Wikimedia Commons API (none when unclear).

DO $$
BEGIN
  INSERT INTO public.historical_facts
    (slug, period_id, title, title_fr, description, description_fr, date_text, date_text_fr,
     year, month, day, region, region_fr, countries, difficulty, tags, tags_fr, points_reward,
     source_url, image_url, image_credit, image_source_url)
  VALUES
    ('reformes-clisthene', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Cleisthenes founds Athenian democracy', 'Clisthène invente la démocratie athénienne',
     'In 508 BCE Cleisthenes reorganised the citizens of Athens into ten tribes and gave power to their assembly: the birth of Athenian democracy.',
     'En 508 av. J.-C., Clisthène réorganise les citoyens d''Athènes en dix tribus et confie le pouvoir à leur assemblée : c''est la naissance de la démocratie athénienne.',
     '508 BCE', '508 av. J.-C.', -508, NULL, NULL, 'europe', 'Europe', ARRAY['GR'], 'medium',
     ARRAY['greece', 'politics'], ARRAY['grèce', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/Clisth%C3%A8ne_(Ath%C3%A8nes)',
     NULL,
     NULL,
     NULL),

    ('bataille-marathon', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Battle of Marathon', 'La bataille de Marathon',
     'In 490 BCE the Athenians drove back the Persian army of Darius I at Marathon. The legend of the messenger who ran to Athens inspired the modern marathon race.',
     'En 490 av. J.-C., les Athéniens repoussent l''armée perse de Darius Ier à Marathon. La légende du messager courant jusqu''à Athènes inspirera l''épreuve moderne du marathon.',
     '490 BCE', '490 av. J.-C.', -490, NULL, NULL, 'europe', 'Europe', ARRAY['GR'], 'easy',
     ARRAY['greece', 'military'], ARRAY['grèce', 'militaire'], 10,
     'https://fr.wikipedia.org/wiki/Bataille_de_Marathon',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Trophee_bataille_marathon.JPG/1280px-Trophee_bataille_marathon.JPG',
     'karta24, CC BY 2.5, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Trophee_bataille_marathon.JPG'),

    ('assassinat-cesar', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The assassination of Julius Caesar', 'L''assassinat de Jules César',
     'On 15 March 44 BCE, the Ides of March, Julius Caesar was stabbed during a session of the Senate by conspirators including his protégé Brutus.',
     'Le 15 mars 44 av. J.-C., aux ides de mars, Jules César est poignardé en pleine séance du Sénat par des conjurés, dont son protégé Brutus.',
     '15 March 44 BCE', '15 mars 44 av. J.-C.', -44, 3, 15, 'europe', 'Europe', ARRAY['IT'], 'easy',
     ARRAY['rome', 'politics'], ARRAY['rome', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/Assassinat_de_Jules_C%C3%A9sar',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_The_Death_of_Caesar_-_Walters_37884.jpg/1280px-Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_The_Death_of_Caesar_-_Walters_37884.jpg',
     'Jean-Léon Gérôme, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_The_Death_of_Caesar_-_Walters_37884.jpg'),

    ('eruption-vesuve', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Vesuvius buries Pompeii', 'L''éruption du Vésuve ensevelit Pompéi',
     'In 79 CE the eruption of Mount Vesuvius buried Pompeii and Herculaneum under ash, freezing these Roman towns until their rediscovery in the 18th century.',
     'En 79, l''éruption du Vésuve recouvre Pompéi et Herculanum de cendres, figeant ces villes romaines jusqu''à leur redécouverte au XVIIIe siècle.',
     '79 CE', '79 apr. J.-C.', 79, NULL, NULL, 'europe', 'Europe', ARRAY['IT'], 'easy',
     ARRAY['rome', 'disaster'], ARRAY['rome', 'catastrophe'], 10,
     'https://fr.wikipedia.org/wiki/Pomp%C3%A9i',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Pompeii_%284873744179%29.jpg/1280px-Pompeii_%284873744179%29.jpg',
     'Glen Scarborough from The Central Coast, Australia, CC BY 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Pompeii_(4873744179).jpg'),

    ('couronnement-charlemagne', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Charlemagne crowned emperor', 'Charlemagne couronné empereur',
     'On 25 December 800 in Rome, Pope Leo III crowned Charlemagne emperor. The king of the Franks then ruled much of western Europe.',
     'Le 25 décembre 800, à Rome, le pape Léon III couronne Charlemagne empereur. Le roi des Francs règne alors sur une grande partie de l''Europe occidentale.',
     '25 December 800', '25 décembre 800', 800, 12, 25, 'europe', 'Europe', ARRAY['FR', 'DE', 'IT'], 'easy',
     ARRAY['franks', 'empire'], ARRAY['francs', 'empire'], 10,
     'https://fr.wikipedia.org/wiki/Charlemagne',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Charlemagne_denier_Mayence_812_814.jpg/1280px-Charlemagne_denier_Mayence_812_814.jpg',
     'Denier de Charlemagne (812-814), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Charlemagne_denier_Mayence_812_814.jpg'),

    ('bataille-hastings', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The Battle of Hastings', 'La bataille d''Hastings',
     'On 14 October 1066 William, Duke of Normandy, defeated King Harold at Hastings and became king of England. The Bayeux Tapestry tells the story of this conquest.',
     'Le 14 octobre 1066, le duc de Normandie Guillaume bat le roi Harold à Hastings et devient roi d''Angleterre. La tapisserie de Bayeux raconte cette conquête.',
     '14 October 1066', '14 octobre 1066', 1066, 10, 14, 'europe', 'Europe', ARRAY['GB'], 'medium',
     ARRAY['england', 'normandy', 'military'], ARRAY['angleterre', 'normandie', 'militaire'], 15,
     'https://fr.wikipedia.org/wiki/Bataille_d%27Hastings',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Bayeux_Tapestry_scene57_Harold_death.jpg/1280px-Bayeux_Tapestry_scene57_Harold_death.jpg',
     'Myrabella, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Bayeux_Tapestry_scene57_Harold_death.jpg'),

    ('magna-carta', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Magna Carta', 'La Magna Carta',
     'On 15 June 1215 the English barons forced King John to accept Magna Carta, which limited royal power. It remains a founding text of civil liberties.',
     'Le 15 juin 1215, les barons anglais imposent au roi Jean sans Terre la Magna Carta, qui limite le pouvoir royal. Elle reste un texte fondateur des libertés.',
     '15 June 1215', '15 juin 1215', 1215, 6, 15, 'europe', 'Europe', ARRAY['GB'], 'medium',
     ARRAY['england', 'law'], ARRAY['angleterre', 'droit'], 15,
     'https://fr.wikipedia.org/wiki/Magna_Carta',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/1280px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg',
     'British Library, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Magna_Carta_(British_Library_Cotton_MS_Augustus_II.106).jpg'),

    ('peste-noire', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The Black Death reaches Europe', 'La Peste noire arrive en Europe',
     'In 1347 the plague reached Europe through Mediterranean ports. Within five years it killed between a third and half of the continent''s population.',
     'En 1347, la peste débarque en Europe par les ports de Méditerranée. En cinq ans, elle tue entre un tiers et la moitié de la population du continent.',
     '1347', '1347', 1347, NULL, NULL, 'europe', 'Europe', ARRAY['IT', 'FR'], 'easy',
     ARRAY['epidemic', 'society'], ARRAY['épidémie', 'société'], 10,
     'https://fr.wikipedia.org/wiki/Peste_noire',
     'https://upload.wikimedia.org/wikipedia/commons/5/55/Doutielt3.jpg',
     'Pierart dou Tielt (fl. 1340-1360), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Doutielt3.jpg'),

    ('jeanne-arc-orleans', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Joan of Arc relieves Orléans', 'Jeanne d''Arc délivre Orléans',
     'On 8 May 1429 the English lifted the siege of Orléans before troops led by 17-year-old Joan of Arc. This turning point of the Hundred Years'' War opened the way to Charles VII''s coronation.',
     'Le 8 mai 1429, les Anglais lèvent le siège d''Orléans face aux troupes menées par Jeanne d''Arc, 17 ans. Ce tournant de la guerre de Cent Ans ouvre la route du sacre de Charles VII.',
     '8 May 1429', '8 mai 1429', 1429, 5, 8, 'europe', 'Europe', ARRAY['FR'], 'easy',
     ARRAY['france', 'hundred years'' war'], ARRAY['france', 'guerre de cent ans'], 10,
     'https://fr.wikipedia.org/wiki/Jeanne_d%27Arc',
     'https://upload.wikimedia.org/wikipedia/commons/6/6e/Contemporaine_afb_jeanne_d_arc.png',
     'Clément de Fauquembergue, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Contemporaine_afb_jeanne_d_arc.png'),

    ('joconde', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Leonardo paints the Mona Lisa', 'Léonard de Vinci peint la Joconde',
     'Around 1503 in Florence, Leonardo da Vinci began the portrait of Lisa Gherardini. He kept reworking it for years; the Mona Lisa is now in the Louvre.',
     'Vers 1503, à Florence, Léonard de Vinci commence le portrait de Lisa Gherardini. Il le retouchera pendant des années ; la Joconde est aujourd''hui au Louvre.',
     'c. 1503', 'Vers 1503', 1503, NULL, NULL, 'europe', 'Europe', ARRAY['IT'], 'easy',
     ARRAY['art', 'italy'], ARRAY['art', 'italie'], 10,
     'https://fr.wikipedia.org/wiki/La_Joconde',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_natural_color.jpg/1280px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_natural_color.jpg',
     'Leonardo da Vinci, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_natural_color.jpg'),

    ('plafond-sixtine', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Michelangelo completes the Sistine Chapel ceiling', 'Michel-Ange achève le plafond de la chapelle Sixtine',
     'From 1508 to 1512 Michelangelo painted the ceiling of the Sistine Chapel in the Vatican, including the famous Creation of Adam, working from scaffolding.',
     'De 1508 à 1512, Michel-Ange peint la voûte de la chapelle Sixtine au Vatican, dont la célèbre Création d''Adam, souvent allongé sur un échafaudage.',
     '1512', '1512', 1512, NULL, NULL, 'europe', 'Europe', ARRAY['IT'], 'easy',
     ARRAY['art', 'italy'], ARRAY['art', 'italie'], 10,
     'https://fr.wikipedia.org/wiki/Plafond_de_la_chapelle_Sixtine',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/CAPPELLA_SISTINA_Ceiling.jpg/1280px-CAPPELLA_SISTINA_Ceiling.jpg',
     'Michelangelo, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:CAPPELLA_SISTINA_Ceiling.jpg'),

    ('theses-luther', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Luther''s Ninety-five Theses', 'Les 95 thèses de Luther',
     'On 31 October 1517 the monk Martin Luther published 95 theses against the sale of indulgences in Wittenberg, the starting point of the Protestant Reformation.',
     'Le 31 octobre 1517, le moine Martin Luther publie à Wittenberg 95 thèses contre la vente des indulgences. C''est le point de départ de la Réforme protestante.',
     '31 October 1517', '31 octobre 1517', 1517, 10, 31, 'europe', 'Europe', ARRAY['DE'], 'medium',
     ARRAY['religion', 'reformation'], ARRAY['religion', 'réforme'], 15,
     'https://fr.wikipedia.org/wiki/95_th%C3%A8ses',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Luther_95_Thesen.png/1280px-Luther_95_Thesen.png',
     'Martin Luther, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Luther_95_Thesen.png'),

    ('copernic-heliocentrisme', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Copernicus puts the Sun at the centre', 'Copernic place le Soleil au centre',
     'In 1543 Nicolaus Copernicus published his book arguing that the Earth revolves around the Sun, not the other way round, an idea that would transform astronomy.',
     'En 1543 paraît le livre de Nicolas Copernic affirmant que la Terre tourne autour du Soleil, et non l''inverse. Cette idée bouleversera l''astronomie.',
     '1543', '1543', 1543, NULL, NULL, 'europe', 'Europe', ARRAY['PL'], 'medium',
     ARRAY['science', 'astronomy'], ARRAY['science', 'astronomie'], 15,
     'https://fr.wikipedia.org/wiki/Nicolas_Copernic',
     'https://upload.wikimedia.org/wikipedia/commons/f/f2/Nikolaus_Kopernikus.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Nikolaus_Kopernikus.jpg'),

    ('galilee-lunes-jupiter', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Galileo discovers Jupiter''s moons', 'Galilée découvre les lunes de Jupiter',
     'On 7 January 1610 Galileo pointed his telescope at Jupiter and saw "stars" orbiting the planet: its four largest moons.',
     'Le 7 janvier 1610, Galilée pointe sa lunette vers Jupiter et y repère des « étoiles » qui tournent autour de la planète : ses quatre plus grandes lunes.',
     '7 January 1610', '7 janvier 1610', 1610, 1, 7, 'europe', 'Europe', ARRAY['IT'], 'medium',
     ARRAY['science', 'astronomy'], ARRAY['science', 'astronomie'], 15,
     'https://fr.wikipedia.org/wiki/Galil%C3%A9e_(savant)',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg/1280px-Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg',
     'Justus Sustermans, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Justus_Sustermans_-_Portrait_of_Galileo_Galilei,_1636.jpg'),

    ('traites-westphalie', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Peace of Westphalia', 'Les traités de Westphalie',
     'On 24 October 1648 the Peace of Westphalia ended the Thirty Years'' War. It set out the principle of sovereign states that still shapes international relations.',
     'Le 24 octobre 1648, les traités de Westphalie mettent fin à la guerre de Trente Ans. Ils posent le principe d''États souverains qui structure encore les relations internationales.',
     '24 October 1648', '24 octobre 1648', 1648, 10, 24, 'europe', 'Europe', ARRAY['DE'], 'hard',
     ARRAY['diplomacy', 'war'], ARRAY['diplomatie', 'guerre'], 20,
     'https://fr.wikipedia.org/wiki/Trait%C3%A9s_de_Westphalie',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Helst%2C_Peace_of_M%C3%BCnster.jpg/1280px-Helst%2C_Peace_of_M%C3%BCnster.jpg',
     'Bartholomeus van der Helst / Jan Vos, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Helst,_Peace_of_M%C3%BCnster.jpg'),

    ('cour-versailles', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Louis XIV moves to Versailles', 'Louis XIV s''installe à Versailles',
     'On 6 May 1682 Louis XIV moved the court and government to the Palace of Versailles, a symbol of absolute monarchy admired across Europe.',
     'Le 6 mai 1682, Louis XIV installe la cour et le gouvernement au château de Versailles, symbole de la monarchie absolue qui fascine toute l''Europe.',
     '6 May 1682', '6 mai 1682', 1682, 5, 6, 'europe', 'Europe', ARRAY['FR'], 'easy',
     ARRAY['france', 'monarchy'], ARRAY['france', 'monarchie'], 10,
     'https://fr.wikipedia.org/wiki/Ch%C3%A2teau_de_Versailles',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_083.jpg/1280px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_083.jpg',
     'ToucanWings, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_083.jpg'),

    ('principia-newton', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Newton publishes the Principia', 'Newton publie les Principia',
     'On 5 July 1687 Isaac Newton published the Principia, setting out the laws of motion and universal gravitation, which explain both a falling apple and the Moon''s orbit.',
     'Le 5 juillet 1687, Isaac Newton publie les Principia, où il énonce les lois du mouvement et la gravitation universelle, qui expliquent aussi bien la chute d''une pomme que l''orbite de la Lune.',
     '5 July 1687', '5 juillet 1687', 1687, 7, 5, 'europe', 'Europe', ARRAY['GB'], 'medium',
     ARRAY['science', 'physics'], ARRAY['science', 'physique'], 15,
     'https://fr.wikipedia.org/wiki/Philosophi%C3%A6_naturalis_principia_mathematica',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Newton%27s_Principia_title_page.png/1280px-Newton%27s_Principia_title_page.png',
     'Page de titre de l''édition de 1687, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Newton%27s_Principia_title_page.png'),

    ('encyclopedie', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The first volume of the Encyclopédie', 'Le premier volume de l''Encyclopédie',
     'In 1751 the first volume of the Encyclopédie edited by Diderot and d''Alembert was published. This great dictionary of knowledge spread the ideas of the Enlightenment.',
     'En 1751 paraît le premier volume de l''Encyclopédie dirigée par Diderot et d''Alembert. Ce grand dictionnaire des savoirs diffuse les idées des Lumières.',
     '1751', '1751', 1751, NULL, NULL, 'europe', 'Europe', ARRAY['FR'], 'medium',
     ARRAY['enlightenment', 'books'], ARRAY['lumières', 'livres'], 15,
     'https://fr.wikipedia.org/wiki/Encyclop%C3%A9die_ou_Dictionnaire_raisonn%C3%A9_des_sciences,_des_arts_et_des_m%C3%A9tiers',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg/1280px-Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg',
     'Diderot et d''Alembert (1751), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg'),

    ('sacre-napoleon', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The coronation of Napoleon', 'Le sacre de Napoléon',
     'On 2 December 1804 at Notre-Dame in Paris, Napoleon Bonaparte crowned himself Emperor of the French in the presence of Pope Pius VII.',
     'Le 2 décembre 1804, à Notre-Dame de Paris, Napoléon Bonaparte se couronne lui-même empereur des Français en présence du pape Pie VII.',
     '2 December 1804', '2 décembre 1804', 1804, 12, 2, 'europe', 'Europe', ARRAY['FR'], 'easy',
     ARRAY['france', 'empire'], ARRAY['france', 'empire'], 10,
     'https://fr.wikipedia.org/wiki/Sacre_de_Napol%C3%A9on_Ier',
     'https://upload.wikimedia.org/wikipedia/commons/1/17/Sacre_de_Napol%C3%A9on_par_Percier_et_Fontaine.png',
     'Charles Percier (1764–1838), Pierre François Léonard Fontaine (1762–1853), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Sacre_de_Napol%C3%A9on_par_Percier_et_Fontaine.png'),

    ('armistice-1918', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Armistice of 11 November 1918', 'L''armistice du 11 novembre 1918',
     'On 11 November 1918 the armistice signed in a railway carriage at Rethondes took effect at 11 a.m., ending the fighting of the First World War on the Western Front.',
     'Le 11 novembre 1918, signé dans un wagon à Rethondes, l''armistice entre en vigueur à 11 heures : les combats de la Première Guerre mondiale cessent sur le front de l''Ouest.',
     '11 November 1918', '11 novembre 1918', 1918, 11, 11, 'europe', 'Europe', ARRAY['FR'], 'easy',
     ARRAY['first world war'], ARRAY['première guerre mondiale'], 10,
     'https://fr.wikipedia.org/wiki/Armistice_du_11_novembre_1918',
     'https://upload.wikimedia.org/wikipedia/commons/2/21/Armisticetrain.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Armisticetrain.jpg'),

    ('traite-rome', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Treaty of Rome', 'Le traité de Rome',
     'On 25 March 1957 six countries — France, West Germany, Italy, Belgium, the Netherlands and Luxembourg — signed the Treaty of Rome creating the European Economic Community.',
     'Le 25 mars 1957, six pays — France, Allemagne de l''Ouest, Italie, Belgique, Pays-Bas et Luxembourg — signent le traité de Rome qui crée la Communauté économique européenne.',
     '25 March 1957', '25 mars 1957', 1957, 3, 25, 'europe', 'Europe', ARRAY['IT', 'FR', 'DE', 'BE', 'NL', 'LU'], 'medium',
     ARRAY['europe', 'politics'], ARRAY['europe', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Rome',
     NULL,
     NULL,
     NULL),

    ('chute-mur-berlin', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The fall of the Berlin Wall', 'La chute du mur de Berlin',
     'On 9 November 1989 East Berliners crossed freely through the Wall that had divided their city since 1961. Germany was reunified a year later.',
     'Le 9 novembre 1989, les Berlinois de l''Est franchissent librement le Mur qui coupait leur ville depuis 1961. Un an plus tard, l''Allemagne est réunifiée.',
     '9 November 1989', '9 novembre 1989', 1989, 11, 9, 'europe', 'Europe', ARRAY['DE'], 'easy',
     ARRAY['cold war', 'germany'], ARRAY['guerre froide', 'allemagne'], 10,
     'https://fr.wikipedia.org/wiki/Chute_du_mur_de_Berlin',
     'https://upload.wikimedia.org/wikipedia/commons/1/1c/West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg',
     'Photographe inconnu, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg'),

    ('confucius', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The birth of Confucius', 'La naissance de Confucius',
     'Born around 551 BCE in the state of Lu, Confucius taught an ethic of respect, learning and duty that shaped China for more than two thousand years.',
     'Né vers 551 av. J.-C. dans l''État de Lu, Confucius enseigne une morale fondée sur le respect, l''étude et le sens du devoir, qui marquera la Chine pendant plus de deux mille ans.',
     'c. 551 BCE', 'Vers 551 av. J.-C.', -551, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'easy',
     ARRAY['china', 'philosophy'], ARRAY['chine', 'philosophie'], 10,
     'https://fr.wikipedia.org/wiki/Confucius',
     'https://upload.wikimedia.org/wikipedia/commons/4/4f/Konfuzius-1770.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Konfuzius-1770.jpg'),

    ('armee-terre-cuite', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Terracotta Army', 'L''armée de terre cuite',
     'When the first emperor Qin Shi Huang died in 210 BCE, he was buried with thousands of life-size terracotta soldiers, found by farmers in 1974.',
     'Mort en 210 av. J.-C., le premier empereur Qin Shi Huang est enterré avec des milliers de soldats grandeur nature en terre cuite, retrouvés par des paysans en 1974.',
     '210 BCE', '210 av. J.-C.', -210, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'easy',
     ARRAY['china', 'archaeology'], ARRAY['chine', 'archéologie'], 10,
     'https://fr.wikipedia.org/wiki/Arm%C3%A9e_de_terre_cuite',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/A_rank_of_terracotta_soldiers.jpg/1280px-A_rank_of_terracotta_soldiers.jpg',
     'High Contrast, CC BY 3.0 DE, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:A_rank_of_terracotta_soldiers.jpg'),

    ('ashoka-kalinga', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Ashoka renounces war', 'Ashoka renonce à la guerre',
     'Around 261 BCE, horrified by the bloodshed of the Kalinga war, the Indian emperor Ashoka turned to Buddhism and had edicts promoting tolerance carved in stone.',
     'Vers 261 av. J.-C., horrifié par le massacre de la guerre de Kalinga, l''empereur indien Ashoka se tourne vers le bouddhisme et fait graver des édits prônant la tolérance.',
     'c. 261 BCE', 'Vers 261 av. J.-C.', -261, NULL, NULL, 'asia', 'Asie', ARRAY['IN'], 'hard',
     ARRAY['india', 'religion'], ARRAY['inde', 'religion'], 20,
     'https://fr.wikipedia.org/wiki/Ashoka',
     'https://upload.wikimedia.org/wikipedia/commons/2/28/Ashoka%27s_visit_to_the_Ramagrama_stupa_Sanchi_Stupa_1_Southern_gateway.jpg',
     'Photo Dharma from Sadao, Thailand, CC BY 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ashoka%27s_visit_to_the_Ramagrama_stupa_Sanchi_Stupa_1_Southern_gateway.jpg'),

    ('zhang-qian-route-soie', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Zhang Qian opens the Silk Road', 'Zhang Qian ouvre la route de la soie',
     'In 138 BCE Emperor Wu of Han sent Zhang Qian to Central Asia. His journeys opened the way for Silk Road trade between China and the West.',
     'En 138 av. J.-C., l''empereur Han Wudi envoie Zhang Qian vers l''Asie centrale. Ses voyages ouvrent la voie aux échanges de la route de la soie entre la Chine et l''Occident.',
     '138 BCE', '138 av. J.-C.', -138, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'hard',
     ARRAY['china', 'trade', 'exploration'], ARRAY['chine', 'commerce', 'exploration'], 20,
     'https://fr.wikipedia.org/wiki/Zhang_Qian',
     'https://upload.wikimedia.org/wikipedia/commons/3/38/ZhangQianTravels.jpg',
     'PHG, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:ZhangQianTravels.jpg'),

    ('imprimerie-bi-sheng', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Bi Sheng invents movable type', 'Bi Sheng invente les caractères mobiles',
     'In the 1040s the Chinese artisan Bi Sheng invented printing with movable type made of baked clay, four centuries before Gutenberg.',
     'Dans les années 1040, l''artisan chinois Bi Sheng invente l''impression à caractères mobiles en argile cuite, quatre siècles avant Gutenberg.',
     'Between 1041 and 1048', 'Entre 1041 et 1048', 1041, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'hard',
     ARRAY['china', 'invention'], ARRAY['chine', 'invention'], 20,
     'https://fr.wikipedia.org/wiki/Bi_Sheng',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Beijing.Musee_imprimerie.caracteres_mobiles.Bisheng.jpg/1280px-Beijing.Musee_imprimerie.caracteres_mobiles.Bisheng.jpg',
     'Popolon, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Beijing.Musee_imprimerie.caracteres_mobiles.Bisheng.jpg'),

    ('angkor-vat', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The building of Angkor Wat', 'La construction d''Angkor Vat',
     'In the early 12th century the Khmer king Suryavarman II built Angkor Wat, dedicated to the god Vishnu. It is now the largest religious monument in the world.',
     'Au début du XIIe siècle, le roi khmer Suryavarman II fait bâtir Angkor Vat, dédié au dieu Vishnou. C''est aujourd''hui le plus grand monument religieux du monde.',
     'Early 12th century', 'Début du XIIe siècle', 1120, NULL, NULL, 'asia', 'Asie', ARRAY['KH'], 'medium',
     ARRAY['cambodia', 'architecture'], ARRAY['cambodge', 'architecture'], 15,
     'https://fr.wikipedia.org/wiki/Angkor_Vat',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Angkor_wat_2025_reflet.jpg/1280px-Angkor_wat_2025_reflet.jpg',
     'Ambralina, CC0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Angkor_wat_2025_reflet.jpg'),

    ('gengis-khan', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Genghis Khan unites the Mongols', 'Gengis Khan unifie les Mongols',
     'In 1206 Temüjin was proclaimed Genghis Khan, ruler of all the Mongols. His and his successors'' conquests created the largest contiguous empire in history.',
     'En 1206, Temüjin est proclamé Gengis Khan, chef de tous les Mongols. Ses conquêtes et celles de ses successeurs forment le plus vaste empire d''un seul tenant de l''histoire.',
     '1206', '1206', 1206, NULL, NULL, 'asia', 'Asie', ARRAY['MN'], 'easy',
     ARRAY['mongolia', 'empire'], ARRAY['mongolie', 'empire'], 10,
     'https://fr.wikipedia.org/wiki/Gengis_Khan',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/YuanEmperorAlbumGenghisPortrait.jpg/1280px-YuanEmperorAlbumGenghisPortrait.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:YuanEmperorAlbumGenghisPortrait.jpg'),

    ('expeditions-zheng-he', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The voyages of Zheng He', 'Les expéditions de Zheng He',
     'In 1405 the Chinese admiral Zheng He set out with a huge fleet on the first of seven voyages that would take him as far as Arabia and the coast of East Africa.',
     'En 1405, l''amiral chinois Zheng He part avec une immense flotte pour la première de ses sept expéditions, qui le mèneront jusqu''en Arabie et sur les côtes de l''Afrique de l''Est.',
     '1405', '1405', 1405, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'medium',
     ARRAY['china', 'exploration'], ARRAY['chine', 'exploration'], 15,
     'https://fr.wikipedia.org/wiki/Zheng_He',
     'https://upload.wikimedia.org/wikipedia/commons/8/8e/Zheng_He.jpg',
     'hassan saeed from Melaka, Malaysia, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Zheng_He.jpg'),

    ('hannibal-alpes', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Hannibal crosses the Alps', 'Hannibal franchit les Alpes',
     'In 218 BCE the Carthaginian general Hannibal crossed the Alps with his army and elephants to attack Rome from the north.',
     'En 218 av. J.-C., le général carthaginois Hannibal traverse les Alpes avec son armée et ses éléphants pour attaquer Rome par le nord.',
     '218 BCE', '218 av. J.-C.', -218, NULL, NULL, 'africa', 'Afrique', ARRAY['TN'], 'easy',
     ARRAY['carthage', 'military'], ARRAY['carthage', 'militaire'], 10,
     'https://fr.wikipedia.org/wiki/Hannibal_Barca',
     'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hannibal_Barca_bust_from_Capua_photo.jpg',
     'Fratelli Alinari, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Hannibal_Barca_bust_from_Capua_photo.jpg'),

    ('bibliotheque-alexandrie', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Library of Alexandria', 'La bibliothèque d''Alexandrie',
     'Around 288 BCE King Ptolemy I founded a library in Alexandria meant to gather all the world''s knowledge. It became the most famous library of antiquity.',
     'Vers 288 av. J.-C., le roi Ptolémée Ier fonde à Alexandrie une bibliothèque qui veut rassembler tous les savoirs du monde. Elle devient la plus célèbre bibliothèque de l''Antiquité.',
     'c. 288 BCE', 'Vers 288 av. J.-C.', -288, NULL, NULL, 'africa', 'Afrique', ARRAY['EG'], 'medium',
     ARRAY['egypt', 'books'], ARRAY['égypte', 'livres'], 15,
     'https://fr.wikipedia.org/wiki/Biblioth%C3%A8que_d%27Alexandrie',
     'https://upload.wikimedia.org/wikipedia/commons/6/64/Ancientlibraryalex.jpg',
     'O. Von Corven, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ancientlibraryalex.jpg'),

    ('mort-cleopatre', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The death of Cleopatra', 'La mort de Cléopâtre',
     'In 30 BCE, defeated by Octavian, Cleopatra VII took her own life. The last queen of the Ptolemaic dynasty, she left Egypt to become a Roman province.',
     'En 30 av. J.-C., vaincue par Octave, Cléopâtre VII se donne la mort. Dernière reine de la dynastie des Ptolémées, elle laisse l''Égypte devenir une province romaine.',
     '30 BCE', '30 av. J.-C.', -30, NULL, NULL, 'africa', 'Afrique', ARRAY['EG'], 'easy',
     ARRAY['egypt', 'rome'], ARRAY['égypte', 'rome'], 10,
     'https://fr.wikipedia.org/wiki/Cl%C3%A9op%C3%A2tre_VII',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Cleopatra_VII%2C_dalla_via_appia_tra_ariccia_e_genzano%2C_40-30_ac_ca._02.JPG/1280px-Cleopatra_VII%2C_dalla_via_appia_tra_ariccia_e_genzano%2C_40-30_ac_ca._02.JPG',
     'Sailko, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Cleopatra_VII,_dalla_via_appia_tra_ariccia_e_genzano,_40-30_ac_ca._02.JPG'),

    ('aksoum-christianisme', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Aksum adopts Christianity', 'Aksoum adopte le christianisme',
     'Around 330 King Ezana of Aksum, in present-day Ethiopia, converted to Christianity, making his kingdom one of the first Christian states in the world.',
     'Vers 330, le roi Ezana d''Aksoum, dans l''actuelle Éthiopie, se convertit au christianisme, faisant de son royaume l''un des premiers États chrétiens du monde.',
     'c. 330', 'Vers 330', 330, NULL, NULL, 'africa', 'Afrique', ARRAY['ET'], 'hard',
     ARRAY['ethiopia', 'religion'], ARRAY['éthiopie', 'religion'], 20,
     'https://fr.wikipedia.org/wiki/Royaume_d%27Aksoum',
     'https://upload.wikimedia.org/wikipedia/commons/f/fa/Kingdom_of_Aksum.png',
     'Trokiodero, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Kingdom_of_Aksum.png'),

    ('universite-quaraouiyine', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The founding of al-Qarawiyyin', 'La fondation d''Al Quaraouiyine',
     'In 859 Fatima al-Fihri founded a mosque in Fez that became a great centre of learning: the University of al-Qarawiyyin, often cited as the oldest still operating.',
     'En 859, Fatima al-Fihri fonde à Fès une mosquée qui devient un grand centre d''enseignement : l''université Al Quaraouiyine, souvent citée comme la plus ancienne encore en activité.',
     '859', '859', 859, NULL, NULL, 'africa', 'Afrique', ARRAY['MA'], 'medium',
     ARRAY['morocco', 'education'], ARRAY['maroc', 'éducation'], 15,
     'https://fr.wikipedia.org/wiki/Universit%C3%A9_Al_Quaraouiyine',
     'https://upload.wikimedia.org/wikipedia/commons/7/74/University_of_Al_Qaraouiyine.jpg',
     'Abdel Hassouni, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:University_of_Al_Qaraouiyine.jpg'),

    ('eglises-lalibela', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The churches of Lalibela', 'Les églises de Lalibela',
     'Around 1200 the Ethiopian king Lalibela had eleven churches carved directly out of volcanic rock, conceived as a new Jerusalem.',
     'Vers 1200, le roi éthiopien Lalibela fait creuser onze églises directement dans la roche volcanique, conçues comme une nouvelle Jérusalem.',
     'c. 1200', 'Vers 1200', 1200, NULL, NULL, 'africa', 'Afrique', ARRAY['ET'], 'medium',
     ARRAY['ethiopia', 'architecture', 'religion'], ARRAY['éthiopie', 'architecture', 'religion'], 15,
     'https://fr.wikipedia.org/wiki/%C3%89glises_rupestres_de_Lalibela',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Lalibela%2C_san_giorgio%2C_esterno_24.jpg/1280px-Lalibela%2C_san_giorgio%2C_esterno_24.jpg',
     'Sailko, CC BY 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Lalibela,_san_giorgio,_esterno_24.jpg'),

    ('grand-zimbabwe', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Great Zimbabwe', 'Le Grand Zimbabwe',
     'At its height in the 14th century, the city of Great Zimbabwe housed thousands of people behind huge stone walls built without mortar. It gave the country its name.',
     'À son apogée au XIVe siècle, la cité du Grand Zimbabwe abrite des milliers d''habitants derrière d''immenses murs de pierre assemblés sans mortier. Elle a donné son nom au pays.',
     '14th century', 'XIVe siècle', 1300, NULL, NULL, 'africa', 'Afrique', ARRAY['ZW'], 'medium',
     ARRAY['zimbabwe', 'architecture'], ARRAY['zimbabwe', 'architecture'], 15,
     'https://fr.wikipedia.org/wiki/Grand_Zimbabwe',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Great-Zimbabwe.jpg/1280px-Great-Zimbabwe.jpg',
     'Jan Derk, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Great-Zimbabwe.jpg'),

    ('voyages-ibn-battuta', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The travels of Ibn Battuta', 'Les voyages d''Ibn Battûta',
     'In 1325 Ibn Battuta left Tangier on pilgrimage to Mecca. He travelled for nearly thirty years, from Africa to China, and recounted it all in a famous travel book.',
     'En 1325, Ibn Battûta quitte Tanger pour le pèlerinage de La Mecque. Il voyagera près de trente ans, de l''Afrique à la Chine, et racontera tout dans un célèbre récit.',
     '1325', '1325', 1325, NULL, NULL, 'africa', 'Afrique', ARRAY['MA'], 'medium',
     ARRAY['morocco', 'exploration'], ARRAY['maroc', 'exploration'], 15,
     'https://fr.wikipedia.org/wiki/Ibn_Batt%C3%BBta',
     'https://upload.wikimedia.org/wikipedia/commons/a/a4/Bust_of_Ibn_Battuta_at_Ibn_Battuta_museum.jpg',
     'Ideophagous, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Bust_of_Ibn_Battuta_at_Ibn_Battuta_museum.jpg'),

    ('arrivee-colomb', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Columbus reaches the Americas', 'Christophe Colomb atteint les Amériques',
     'On 12 October 1492, after more than two months at sea, Christopher Columbus''s expedition landed in the Bahamas. He believed he had reached Asia.',
     'Le 12 octobre 1492, après plus de deux mois de traversée, l''expédition de Christophe Colomb accoste dans les Bahamas. Il croit être arrivé en Asie.',
     '12 October 1492', '12 octobre 1492', 1492, 10, 12, 'americas', 'Amériques', ARRAY['BS'], 'easy',
     ARRAY['exploration', 'spain'], ARRAY['exploration', 'espagne'], 10,
     'https://fr.wikipedia.org/wiki/Christophe_Colomb',
     'https://upload.wikimedia.org/wikipedia/commons/0/05/Ridolfo_del_Ghirlandaio_-_Ritratto_di_Cristoforo_Colombo_%281520%29.jpg',
     'Ridolfo del Ghirlandaio, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ridolfo_del_Ghirlandaio_-_Ritratto_di_Cristoforo_Colombo_(1520).jpg'),

    ('chute-tenochtitlan', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The fall of Tenochtitlan', 'La chute de Tenochtitlan',
     'On 13 August 1521, after a long siege, Hernán Cortés and his Indigenous allies took Tenochtitlan, the Aztec capital. Mexico City was built on its ruins.',
     'Le 13 août 1521, après un long siège, Hernán Cortés et ses alliés indigènes prennent Tenochtitlan, la capitale aztèque. Mexico sera bâtie sur ses ruines.',
     '13 August 1521', '13 août 1521', 1521, 8, 13, 'americas', 'Amériques', ARRAY['MX'], 'medium',
     ARRAY['aztecs', 'conquest'], ARRAY['aztèques', 'conquête'], 15,
     'https://fr.wikipedia.org/wiki/Si%C3%A8ge_de_Tenochtitlan',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png/1280px-Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png'),

    ('fondation-quebec', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Champlain founds Quebec', 'Champlain fonde Québec',
     'On 3 July 1608 Samuel de Champlain founded Quebec on the banks of the St. Lawrence River. The town became the heart of New France.',
     'Le 3 juillet 1608, Samuel de Champlain fonde Québec sur les rives du Saint-Laurent. La ville devient le cœur de la Nouvelle-France.',
     '3 July 1608', '3 juillet 1608', 1608, 7, 3, 'americas', 'Amériques', ARRAY['CA'], 'easy',
     ARRAY['canada', 'new france'], ARRAY['canada', 'nouvelle-france'], 10,
     'https://fr.wikipedia.org/wiki/Samuel_de_Champlain',
     'https://upload.wikimedia.org/wikipedia/commons/9/97/Samchamprifle.jpg',
     'Samuel de Champlain, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Samchamprifle.jpg'),

    ('mayflower', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Mayflower reaches America', 'Le Mayflower arrive en Amérique',
     'In 1620 the Mayflower landed about a hundred English settlers, the Pilgrims, on the Massachusetts coast, where they founded Plymouth Colony.',
     'En 1620, le Mayflower débarque une centaine de colons anglais, les Pères pèlerins, sur la côte du Massachusetts, où ils fondent la colonie de Plymouth.',
     '1620', '1620', 1620, NULL, NULL, 'americas', 'Amériques', ARRAY['US'], 'medium',
     ARRAY['united states', 'colonisation'], ARRAY['états-unis', 'colonisation'], 15,
     'https://fr.wikipedia.org/wiki/Mayflower',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Mayflower_in_Plymouth_Harbor%2C_by_William_Halsall.jpg/1280px-Mayflower_in_Plymouth_Harbor%2C_by_William_Halsall.jpg',
     'William Halsall, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Mayflower_in_Plymouth_Harbor,_by_William_Halsall.jpg'),

    ('declaration-independance', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The American Declaration of Independence', 'La Déclaration d''indépendance américaine',
     'On 4 July 1776 the thirteen British colonies in America adopted the Declaration of Independence, drafted largely by Thomas Jefferson.',
     'Le 4 juillet 1776, les treize colonies britanniques d''Amérique adoptent la Déclaration d''indépendance, rédigée en grande partie par Thomas Jefferson.',
     '4 July 1776', '4 juillet 1776', 1776, 7, 4, 'americas', 'Amériques', ARRAY['US'], 'easy',
     ARRAY['united states', 'revolution'], ARRAY['états-unis', 'révolution'], 10,
     'https://fr.wikipedia.org/wiki/D%C3%A9claration_d%27ind%C3%A9pendance_des_%C3%89tats-Unis',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/United_States_Declaration_of_Independence.jpg/1280px-United_States_Declaration_of_Independence.jpg',
     'William Stone (gravure, 1823), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:United_States_Declaration_of_Independence.jpg'),

    ('hegire', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The Hijra', 'L''Hégire',
     'In 622 the Prophet Muhammad left Mecca for Medina with his followers. This migration, the Hijra, marks the start of the Islamic calendar.',
     'En 622, le prophète Mahomet quitte La Mecque pour Médine avec ses fidèles. Cet exil, l''Hégire, marque le début du calendrier musulman.',
     '622', '622', 622, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['SA'], 'easy',
     ARRAY['islam', 'religion'], ARRAY['islam', 'religion'], 10,
     'https://fr.wikipedia.org/wiki/H%C3%A9gire',
     NULL,
     NULL,
     NULL),

    ('fondation-bagdad', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The founding of Baghdad', 'La fondation de Bagdad',
     'In 762 the Abbasid caliph al-Mansur founded Baghdad on the Tigris, around a circular city. It became one of the largest cities in the world.',
     'En 762, le calife abbasside al-Mansur fonde Bagdad sur le Tigre, autour d''une ville ronde. Elle devient l''une des plus grandes villes du monde.',
     '762', '762', 762, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ'], 'medium',
     ARRAY['iraq', 'islam'], ARRAY['irak', 'islam'], 15,
     'https://fr.wikipedia.org/wiki/Ville_ronde_de_Bagdad',
     'https://upload.wikimedia.org/wikipedia/commons/c/cb/Ville_ronde.png',
     'Gael146, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ville_ronde.png'),

    ('maison-sagesse', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Baghdad, capital of learning', 'Bagdad, capitale du savoir',
     'In the 9th century Baghdad became a great centre for translating Greek texts into Arabic, often linked to the "House of Wisdom", whose scale is debated. The mathematician al-Khwarizmi laid the foundations of algebra there.',
     'Au IXe siècle, Bagdad devient un grand centre de traduction des textes grecs en arabe, souvent associé à la « Maison de la sagesse », dont l''ampleur est débattue. Le mathématicien al-Khwârizmî y pose les bases de l''algèbre.',
     '9th century', 'IXe siècle', 830, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ'], 'hard',
     ARRAY['science', 'iraq'], ARRAY['science', 'irak'], 20,
     'https://fr.wikipedia.org/wiki/Maison_de_la_sagesse',
     'https://upload.wikimedia.org/wikipedia/commons/2/2c/Maqamat_hariri.jpg',
     'Zereshk, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Maqamat_hariri.jpg'),

    ('saladin-jerusalem', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Saladin takes Jerusalem', 'Saladin prend Jérusalem',
     'On 2 October 1187 Sultan Saladin took Jerusalem back from the Crusaders, who had held it since 1099. Its loss triggered the Third Crusade.',
     'Le 2 octobre 1187, le sultan Saladin reprend Jérusalem aux croisés, qui la tenaient depuis 1099. Cette perte provoque la troisième croisade.',
     '2 October 1187', '2 octobre 1187', 1187, 10, 2, 'middle-east', 'Moyen-Orient', ARRAY['IL', 'PS'], 'medium',
     ARRAY['crusades', 'military'], ARRAY['croisades', 'militaire'], 15,
     'https://fr.wikipedia.org/wiki/Si%C3%A8ge_de_J%C3%A9rusalem_(1187)',
     'https://upload.wikimedia.org/wikipedia/commons/8/83/ChristiansBeforeSaladin.jpg',
     'Alphonse de Neuville, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:ChristiansBeforeSaladin.jpg'),

    ('chute-constantinople', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The fall of Constantinople', 'La chute de Constantinople',
     'On 29 May 1453 the Ottoman sultan Mehmed II took Constantinople after a siege of nearly two months, ending the Byzantine Empire; the city would become Istanbul.',
     'Le 29 mai 1453, le sultan ottoman Mehmed II prend Constantinople après un siège de près de deux mois. C''est la fin de l''Empire byzantin ; la ville deviendra Istanbul.',
     '29 May 1453', '29 mai 1453', 1453, 5, 29, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'easy',
     ARRAY['ottoman empire', 'byzantium'], ARRAY['empire ottoman', 'byzance'], 10,
     'https://fr.wikipedia.org/wiki/Chute_de_Constantinople',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Benjamin-Constant-The_Entry_of_Mahomet_II_into_Constantinople-1876.jpg/1280px-Benjamin-Constant-The_Entry_of_Mahomet_II_into_Constantinople-1876.jpg',
     'Jean-Joseph Benjamin-Constant, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Benjamin-Constant-The_Entry_of_Mahomet_II_into_Constantinople-1876.jpg'),

    ('abolition-esclavage-usa', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The United States abolishes slavery', 'Les États-Unis abolissent l''esclavage',
     'On 6 December 1865 the 13th Amendment to the Constitution was ratified, abolishing slavery throughout the United States months after the end of the Civil War.',
     'Le 6 décembre 1865, le 13e amendement de la Constitution est ratifié : l''esclavage est aboli dans tous les États-Unis, quelques mois après la fin de la guerre de Sécession.',
     '6 December 1865', '6 décembre 1865', 1865, 12, 6, 'americas', 'Amériques', ARRAY['US'], 'medium',
     ARRAY['united states', 'rights'], ARRAY['états-unis', 'droits'], 15,
     'https://fr.wikipedia.org/wiki/Treizi%C3%A8me_amendement_de_la_Constitution_des_%C3%89tats-Unis',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/AdoptionOf13thAmendment.jpg/1280px-AdoptionOf13thAmendment.jpg',
     'Harper''s Weekly (1865), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:AdoptionOf13thAmendment.jpg'),

    ('canal-panama', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Panama Canal opens', 'L''ouverture du canal de Panama',
     'On 15 August 1914 the Panama Canal opened. Ships could now sail from the Atlantic to the Pacific without going around South America.',
     'Le 15 août 1914, le canal de Panama est inauguré. Les navires passent désormais de l''Atlantique au Pacifique sans contourner l''Amérique du Sud.',
     '15 August 1914', '15 août 1914', 1914, 8, 15, 'americas', 'Amériques', ARRAY['PA'], 'easy',
     ARRAY['panama', 'transport'], ARRAY['panama', 'transport'], 10,
     'https://fr.wikipedia.org/wiki/Canal_de_Panama',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Panama_Canal_Map_FR.png/1280px-Panama_Canal_Map_FR.png',
     'Thoroe, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Panama_Canal_Map_FR.png'),

    ('krach-1929', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Wall Street Crash', 'Le krach de 1929',
     'On 24 October 1929, "Black Thursday", the New York Stock Exchange collapsed. The crisis that followed, the Great Depression, spread around the world.',
     'Le 24 octobre 1929, le « jeudi noir », la Bourse de New York s''effondre. La crise qui suit, la Grande Dépression, touche le monde entier.',
     '24 October 1929', '24 octobre 1929', 1929, 10, 24, 'americas', 'Amériques', ARRAY['US'], 'medium',
     ARRAY['economy', 'united states'], ARRAY['économie', 'états-unis'], 15,
     'https://fr.wikipedia.org/wiki/Krach_de_1929',
     'https://upload.wikimedia.org/wikipedia/commons/e/e1/Crowd_outside_nyse.jpg',
     'US-gov, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Crowd_outside_nyse.jpg'),

    ('apollo-11', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The first steps on the Moon', 'Les premiers pas sur la Lune',
     'On 20 July 1969 the Apollo 11 lunar module landed on the Moon. A few hours later Neil Armstrong became the first person to walk on it.',
     'Le 20 juillet 1969, le module lunaire d''Apollo 11 se pose sur la Lune. Quelques heures plus tard, Neil Armstrong devient le premier homme à y marcher.',
     '20 July 1969', '20 juillet 1969', 1969, 7, 20, 'americas', 'Amériques', ARRAY['US'], 'easy',
     ARRAY['space', 'united states'], ARRAY['espace', 'états-unis'], 10,
     'https://fr.wikipedia.org/wiki/Apollo_11',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Apollo_11_insignia.png/1280px-Apollo_11_insignia.png',
     'NASA, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Apollo_11_insignia.png')
  ON CONFLICT (slug) DO UPDATE SET
    period_id = EXCLUDED.period_id,
    title = EXCLUDED.title,
    title_fr = EXCLUDED.title_fr,
    description = EXCLUDED.description,
    description_fr = EXCLUDED.description_fr,
    date_text = EXCLUDED.date_text,
    date_text_fr = EXCLUDED.date_text_fr,
    year = EXCLUDED.year,
    month = EXCLUDED.month,
    day = EXCLUDED.day,
    region = EXCLUDED.region,
    region_fr = EXCLUDED.region_fr,
    countries = EXCLUDED.countries,
    difficulty = EXCLUDED.difficulty,
    tags = EXCLUDED.tags,
    tags_fr = EXCLUDED.tags_fr,
    points_reward = EXCLUDED.points_reward,
    source_url = EXCLUDED.source_url,
    image_url = EXCLUDED.image_url,
    image_credit = EXCLUDED.image_credit,
    image_source_url = EXCLUDED.image_source_url;
END
$$;
