-- Content batch 2: 81 facts for the region x era themes batch 1 left empty
-- or thin (Prehistory, Oceania, Asia, Africa and the Middle East in modern
-- times, the early Americas), about five facts per theme.
-- Same rerunnable upsert format as 001_demo_facts.sql (keyed on slug).
-- source_url is the French Wikipedia article each text was written from; every
-- year was cross-checked against it. Images are the article's lead image, with
-- author and license read from the Wikimedia Commons API (none when unclear).

DO $$
BEGIN
  INSERT INTO public.historical_facts
    (slug, period_id, title, title_fr, description, description_fr, date_text, date_text_fr,
     year, month, day, region, region_fr, countries, difficulty, tags, tags_fr, points_reward,
     source_url, image_url, image_credit, image_source_url)
  VALUES
    ('grotte-chauvet', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The paintings of Chauvet Cave', 'Les peintures de la grotte Chauvet',
     'About 36,000 years ago, Palaeolithic artists painted lions, rhinoceroses and horses on the walls of Chauvet Cave in the Ardèche. Rediscovered in 1994, it holds some of the oldest known figurative paintings.',
     'Il y a environ 36 000 ans, des artistes du Paléolithique peignent lions, rhinocéros et chevaux sur les parois de la grotte Chauvet, en Ardèche. Redécouverte en 1994, elle abrite certaines des plus anciennes peintures figuratives connues.',
     'About 36,000 years ago', 'Il y a environ 36 000 ans', -34000, NULL, NULL, 'europe', 'Europe', ARRAY['FR'], 'medium',
     ARRAY['art', 'palaeolithic'], ARRAY['art', 'paléolithique'], 15,
     'https://fr.wikipedia.org/wiki/Grotte_Chauvet',
     'https://upload.wikimedia.org/wikipedia/commons/5/54/Chauvethorses.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Chauvethorses.jpg'),

    ('grotte-lascaux', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The Lascaux Cave', 'La grotte de Lascaux',
     'About 17,000 years ago, Palaeolithic people covered the Lascaux Cave in the Dordogne with hundreds of painted and engraved animals. It was discovered in 1940 by four teenagers.',
     'Il y a environ 17 000 ans, des hommes du Paléolithique couvrent la grotte de Lascaux, en Dordogne, de centaines d''animaux peints et gravés. Elle a été découverte en 1940 par quatre adolescents.',
     'About 17,000 years ago', 'Il y a environ 17 000 ans', -15000, NULL, NULL, 'europe', 'Europe', ARRAY['FR'], 'easy',
     ARRAY['art', 'palaeolithic'], ARRAY['art', 'paléolithique'], 10,
     'https://fr.wikipedia.org/wiki/Grotte_de_Lascaux',
     'https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Lascaux_painting.jpg'),

    ('venus-willendorf', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The Venus of Willendorf', 'La Vénus de Willendorf',
     'About 30,000 years ago, an artist carved an 11 cm female figurine with generous curves out of limestone. Found in 1908 in Austria, the Venus of Willendorf is one of the most famous works of prehistory.',
     'Il y a environ 30 000 ans, un artiste sculpte dans le calcaire une statuette féminine de 11 cm aux formes généreuses. Retrouvée en 1908 en Autriche, la Vénus de Willendorf est l''une des plus célèbres œuvres de la Préhistoire.',
     'About 30,000 years ago', 'Il y a environ 30 000 ans', -28000, NULL, NULL, 'europe', 'Europe', ARRAY['AT'], 'medium',
     ARRAY['art', 'palaeolithic'], ARRAY['art', 'paléolithique'], 15,
     'https://fr.wikipedia.org/wiki/V%C3%A9nus_de_Willendorf',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Venus_of_Willendorf_03.jpg/1280px-Venus_of_Willendorf_03.jpg',
     'Matthias Kabel, CC BY 2.5, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Venus_of_Willendorf_03.jpg'),

    ('otzi', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'Ötzi the Iceman', 'Ötzi, l''homme des glaces',
     'Around 3300 BCE, a man died in the Alps with an arrowhead lodged in his shoulder. Preserved by the ice along with his clothes and copper axe, Ötzi was found by two hikers in 1991.',
     'Vers 3300 av. J.-C., un homme meurt dans les Alpes, une pointe de flèche plantée dans l''épaule. Conservé par la glace avec ses vêtements et sa hache de cuivre, Ötzi a été retrouvé en 1991 par deux randonneurs.',
     'c. 3300 BCE', 'Vers 3300 av. J.-C.', -3300, NULL, NULL, 'europe', 'Europe', ARRAY['IT', 'AT'], 'easy',
     ARRAY['archaeology', 'alps'], ARRAY['archéologie', 'alpes'], 10,
     'https://fr.wikipedia.org/wiki/%C3%96tzi',
     'https://upload.wikimedia.org/wikipedia/commons/e/ee/Otzi-Quinson.jpg',
     '120, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Otzi-Quinson.jpg'),

    ('fin-neandertal', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The disappearance of the Neanderthals', 'La disparition de l''homme de Néandertal',
     'About 40,000 years ago, the Neanderthals vanished from Europe after hundreds of thousands of years there. They had interbred with Homo sapiens: people outside Africa still carry 1 to 2% of their DNA.',
     'Il y a environ 40 000 ans, l''homme de Néandertal disparaît d''Europe après des centaines de milliers d''années de présence. Il s''était pourtant mêlé à Homo sapiens : les humains non africains portent encore 1 à 2 % de son ADN.',
     'About 40,000 years ago', 'Il y a environ 40 000 ans', -38000, NULL, NULL, 'europe', 'Europe', ARRAY['DE', 'FR', 'ES'], 'medium',
     ARRAY['evolution', 'humankind'], ARRAY['évolution', 'humanité'], 15,
     'https://fr.wikipedia.org/wiki/Homme_de_N%C3%A9andertal',
     'https://upload.wikimedia.org/wikipedia/commons/e/e0/Homo_sapiens_neanderthalensis.jpg',
     'Luna04, CC BY 2.5, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Homo_sapiens_neanderthalensis.jpg'),

    ('toumai', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'Toumaï, a very distant ancestor', 'Toumaï, un très lointain ancêtre',
     'About 7 million years ago, Toumaï lived in what is now Chad; his skull was found in 2001 in the Djurab Desert. He may be one of the oldest known members of the human lineage.',
     'Il y a environ 7 millions d''années vivait au Tchad Toumaï, dont le crâne a été découvert en 2001 dans le désert du Djourab. Il pourrait être l''un des plus anciens représentants connus de la lignée humaine.',
     'About 7 million years ago', 'Il y a environ 7 millions d''années', -7000000, NULL, NULL, 'africa', 'Afrique', ARRAY['TD'], 'hard',
     ARRAY['evolution', 'fossil'], ARRAY['évolution', 'fossile'], 20,
     'https://fr.wikipedia.org/wiki/Touma%C3%AF',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Sahelanthropus_tchadensis_-_TM_266-01-060-1.jpg/1280px-Sahelanthropus_tchadensis_-_TM_266-01-060-1.jpg',
     'Didier Descouens, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Sahelanthropus_tchadensis_-_TM_266-01-060-1.jpg'),

    ('lucy', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'Lucy the australopithecine', 'Lucy, l''australopithèque',
     'About 3.2 million years ago, Lucy, an australopithecine who already walked upright, lived in Ethiopia. Her skeleton, found in 1974, was named after the Beatles song Lucy in the Sky with Diamonds.',
     'Il y a environ 3,2 millions d''années vivait en Éthiopie Lucy, une australopithèque qui marchait déjà debout. Son squelette, découvert en 1974, doit son nom à la chanson des Beatles Lucy in the Sky with Diamonds.',
     'About 3.2 million years ago', 'Il y a environ 3,2 millions d''années', -3200000, NULL, NULL, 'africa', 'Afrique', ARRAY['ET'], 'easy',
     ARRAY['evolution', 'fossil'], ARRAY['évolution', 'fossile'], 10,
     'https://fr.wikipedia.org/wiki/Lucy_(australopith%C3%A8que)',
     'https://upload.wikimedia.org/wikipedia/commons/e/e0/Reconstruction_of_the_fossil_skeleton_of_%22Lucy%22_the_Australopithecus_afarensis.jpg',
     '120, CC BY 2.5, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Reconstruction_of_the_fossil_skeleton_of_%22Lucy%22_the_Australopithecus_afarensis.jpg'),

    ('djebel-irhoud', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The oldest known Homo sapiens', 'Les plus anciens Homo sapiens connus',
     'About 300,000 years ago, the oldest known Homo sapiens lived at Jebel Irhoud in Morocco. Their dating, published in 2017, pushed the origin of our species back by 100,000 years.',
     'Il y a environ 300 000 ans vivaient au Djebel Irhoud, au Maroc, les plus anciens Homo sapiens connus. Leur datation, publiée en 2017, a reculé de 100 000 ans l''apparition de notre espèce.',
     'About 300,000 years ago', 'Il y a environ 300 000 ans', -300000, NULL, NULL, 'africa', 'Afrique', ARRAY['MA'], 'hard',
     ARRAY['evolution', 'fossil'], ARRAY['évolution', 'fossile'], 20,
     'https://fr.wikipedia.org/wiki/Djebel_Irhoud',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Jebel_Irhoud_1._Homo_Sapiens.jpg/1280px-Jebel_Irhoud_1._Homo_Sapiens.jpg',
     'Ryan Somma, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Jebel_Irhoud_1._Homo_Sapiens.jpg'),

    ('grotte-blombos', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The oldest known drawing', 'Le plus ancien dessin connu',
     'About 73,000 years ago, in Blombos Cave in South Africa, someone drew crossed lines on a stone flake with an ochre crayon. It is the oldest known drawing made by humans.',
     'Il y a environ 73 000 ans, dans la grotte de Blombos, en Afrique du Sud, quelqu''un trace au crayon d''ocre des lignes croisées sur un éclat de pierre. C''est le plus ancien dessin connu de l''humanité.',
     'About 73,000 years ago', 'Il y a environ 73 000 ans', -71000, NULL, NULL, 'africa', 'Afrique', ARRAY['ZA'], 'hard',
     ARRAY['art', 'palaeolithic'], ARRAY['art', 'paléolithique'], 20,
     'https://fr.wikipedia.org/wiki/Grotte_de_Blombos',
     'https://upload.wikimedia.org/wikipedia/commons/f/f9/Blombos.jpg',
     'Vincent Mourre / Inrap, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Blombos.jpg'),

    ('outils-lomekwi', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The oldest stone tools', 'Les plus anciens outils de pierre',
     'About 3.3 million years ago in Kenya, hominins knapped stones to make tools. Found in 2011 at Lomekwi, near Lake Turkana, they are older than the genus Homo itself.',
     'Il y a environ 3,3 millions d''années, au Kenya, des hominines taillent des pierres pour en faire des outils. Découverts en 2011 à Lomekwi, près du lac Turkana, ils sont plus anciens que le genre Homo lui-même.',
     'About 3.3 million years ago', 'Il y a environ 3,3 millions d''années', -3300000, NULL, NULL, 'africa', 'Afrique', ARRAY['KE'], 'hard',
     ARRAY['evolution', 'technology'], ARRAY['évolution', 'technique'], 20,
     'https://fr.wikipedia.org/wiki/Lomekwi_3',
     'https://upload.wikimedia.org/wikipedia/commons/9/98/Lake_turkana_satellite.jpg',
     'NASA, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Lake_turkana_satellite.jpg'),

    ('natoufiens', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The Natufians, the first villagers', 'Les Natoufiens, premiers villageois',
     'Around 12,500 BCE in the Levant, the Natufians built stone houses and settled in villages all year round. They were among the first settled humans, even before farming was invented.',
     'Vers 12 500 av. J.-C., au Levant, les Natoufiens bâtissent des maisons en pierre et s''installent à l''année dans des villages. Ils sont parmi les premiers humains sédentaires, avant même l''invention de l''agriculture.',
     'c. 12,500 BCE', 'Vers 12 500 av. J.-C.', -12500, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IL', 'JO', 'SY'], 'hard',
     ARRAY['neolithic', 'society'], ARRAY['néolithique', 'société'], 20,
     'https://fr.wikipedia.org/wiki/Natoufien',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/NatufianSpread.svg/1280px-NatufianSpread.svg.png',
     'Crates, CC BY 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:NatufianSpread.svg'),

    ('gobekli-tepe', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'Göbekli Tepe, the oldest sanctuary', 'Göbekli Tepe, le plus ancien sanctuaire',
     'Around 9300 BCE, in what is now Turkey, hunter-gatherers raised carved stone pillars weighing several tonnes. Göbekli Tepe is often described as the oldest known monumental sanctuary.',
     'Vers 9300 av. J.-C., dans l''actuelle Turquie, des chasseurs-cueilleurs dressent des piliers de pierre sculptés de plusieurs tonnes. Göbekli Tepe est souvent présenté comme le plus ancien sanctuaire monumental connu.',
     'c. 9300 BCE', 'Vers 9300 av. J.-C.', -9300, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'medium',
     ARRAY['neolithic', 'religion'], ARRAY['néolithique', 'religion'], 15,
     'https://fr.wikipedia.org/wiki/G%C3%B6bekli_Tepe',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/G%C3%B6bekli_Tepe%2C_Urfa.jpg/1280px-G%C3%B6bekli_Tepe%2C_Urfa.jpg',
     'Teomancimit, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:G%C3%B6bekli_Tepe,_Urfa.jpg'),

    ('naissance-agriculture', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The birth of farming', 'La naissance de l''agriculture',
     'Around 9500 BCE, in the Fertile Crescent, communities began to grow wheat and barley. This Neolithic Revolution gradually turned hunter-gatherers into settled farmers.',
     'Vers 9500 av. J.-C., dans le Croissant fertile, des communautés commencent à cultiver le blé et l''orge. Cette révolution néolithique transforme peu à peu les chasseurs-cueilleurs en paysans sédentaires.',
     'c. 9500 BCE', 'Vers 9500 av. J.-C.', -9500, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ', 'SY', 'TR'], 'easy',
     ARRAY['neolithic', 'farming'], ARRAY['néolithique', 'agriculture'], 10,
     'https://fr.wikipedia.org/wiki/Croissant_fertile',
     'https://upload.wikimedia.org/wikipedia/commons/2/22/Fertile_Crescent_concept_1916.png',
     'James Henry Breasted, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Fertile_Crescent_concept_1916.png'),

    ('tour-jericho', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The Tower of Jericho', 'La tour de Jéricho',
     'Around 8300 BCE, the people of Jericho built a stone tower more than 8 metres high, with an internal staircase. It is one of the oldest monumental buildings in the world.',
     'Vers 8300 av. J.-C., les habitants de Jéricho élèvent une tour de pierre de plus de 8 mètres, avec un escalier intérieur. C''est l''une des plus anciennes constructions monumentales au monde.',
     'c. 8300 BCE', 'Vers 8300 av. J.-C.', -8300, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['PS'], 'medium',
     ARRAY['neolithic', 'architecture'], ARRAY['néolithique', 'architecture'], 15,
     'https://fr.wikipedia.org/wiki/Tour_de_J%C3%A9richo',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Tower_of_Jericho.jpg/1280px-Tower_of_Jericho.jpg',
     'Reinhard Dietrich, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Tower_of_Jericho.jpg'),

    ('catal-hoyuk', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'Çatalhöyük, a town without streets', 'Çatal Höyük, une ville sans rues',
     'Around 7100 BCE, Çatalhöyük grew up in Anatolia, one of the largest settlements of the Neolithic. Its houses were packed so tightly together that people entered them through the roof.',
     'Vers 7100 av. J.-C., en Anatolie, naît Çatal Höyük, l''une des plus grandes agglomérations du Néolithique. Ses maisons étaient serrées les unes contre les autres : on y entrait par le toit.',
     'c. 7100 BCE', 'Vers 7100 av. J.-C.', -7100, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'medium',
     ARRAY['neolithic', 'city'], ARRAY['néolithique', 'ville'], 15,
     'https://fr.wikipedia.org/wiki/%C3%87atal_H%C3%B6y%C3%BCk',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/%C3%87atalh%C3%B6y%C3%BCk%2C_7400_BC%2C_Konya%2C_Turkey_-_UNESCO_World_Heritage_Site%2C_08.jpg/1280px-%C3%87atalh%C3%B6y%C3%BCk%2C_7400_BC%2C_Konya%2C_Turkey_-_UNESCO_World_Heritage_Site%2C_08.jpg',
     'Murat Özsoy, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:%C3%87atalh%C3%B6y%C3%BCk,_7400_BC,_Konya,_Turkey_-_UNESCO_World_Heritage_Site,_08.jpg'),

    ('arrivee-australie', (SELECT id FROM public.historical_periods WHERE name = 'Préhistoire'),
     'The first Australians', 'Les premiers habitants de l''Australie',
     'At least 50,000 years ago, people from South-East Asia crossed the sea to Australia. Their descendants, the Aboriginal peoples, have one of the oldest living cultures in the world.',
     'Il y a au moins 50 000 ans, des humains venus d''Asie du Sud-Est traversent la mer jusqu''en Australie. Leurs descendants, les Aborigènes, forment l''une des plus anciennes cultures vivantes du monde.',
     'At least 50,000 years ago', 'Il y a au moins 50 000 ans', -48000, NULL, NULL, 'oceania', 'Océanie', ARRAY['AU'], 'medium',
     ARRAY['settlement', 'aboriginal'], ARRAY['peuplement', 'aborigènes'], 15,
     'https://fr.wikipedia.org/wiki/Aborig%C3%A8nes_d%27Australie',
     'https://upload.wikimedia.org/wikipedia/commons/4/43/Bradshaw_rock_paintings.jpg',
     'TimJN1, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Bradshaw_rock_paintings.jpg'),

    ('arrivee-maoris', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The Māori reach New Zealand', 'Les Maoris arrivent en Nouvelle-Zélande',
     'Around 1280, Polynesian navigators reached New Zealand in large canoes. Their descendants, the Māori, settled one of the last large landmasses ever reached by humans.',
     'Vers 1280, des navigateurs polynésiens atteignent la Nouvelle-Zélande à bord de grandes pirogues. Leurs descendants, les Maoris, peuplent ainsi l''une des dernières grandes terres découvertes par l''humanité.',
     'c. 1280', 'Vers 1280', 1280, NULL, NULL, 'oceania', 'Océanie', ARRAY['NZ'], 'medium',
     ARRAY['polynesia', 'navigation'], ARRAY['polynésie', 'navigation'], 15,
     'https://fr.wikipedia.org/wiki/Maoris',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/New_Zealand_-_Maori_rowing_-_8444.jpg/1280px-New_Zealand_-_Maori_rowing_-_8444.jpg',
     'Jorge Royan, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:New_Zealand_-_Maori_rowing_-_8444.jpg'),

    ('moai', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The moai of Easter Island', 'Les moaïs de l''île de Pâques',
     'Between about 1250 and 1500, the people of Easter Island carved nearly 900 giant statues, the moai. Cut from volcanic rock, they are thought to represent deified ancestors.',
     'Entre 1250 et 1500 environ, les habitants de l''île de Pâques sculptent près de 900 statues géantes, les moaïs. Taillées dans la roche volcanique, elles représenteraient des ancêtres divinisés.',
     'Between 1250 and 1500', 'Entre 1250 et 1500', 1250, NULL, NULL, 'oceania', 'Océanie', ARRAY['CL'], 'easy',
     ARRAY['polynesia', 'art'], ARRAY['polynésie', 'art'], 10,
     'https://fr.wikipedia.org/wiki/Moa%C3%AF',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Ahu_Tongariki.jpg/1280px-Ahu_Tongariki.jpg',
     'Rivi, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ahu_Tongariki.jpg'),

    ('voyage-tasman', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Abel Tasman reaches New Zealand', 'Abel Tasman découvre la Nouvelle-Zélande',
     'In 1642 the Dutch navigator Abel Tasman sailed past Tasmania and then reached New Zealand. He was the first known European to see these lands, which still bear his name or that of his country.',
     'En 1642, le navigateur néerlandais Abel Tasman longe la Tasmanie puis atteint la Nouvelle-Zélande. Il est le premier Européen connu à voir ces terres, qui portent encore son nom ou celui de son pays.',
     '1642', '1642', 1642, NULL, NULL, 'oceania', 'Océanie', ARRAY['AU', 'NZ'], 'medium',
     ARRAY['exploration', 'navigation'], ARRAY['exploration', 'navigation'], 15,
     'https://fr.wikipedia.org/wiki/Abel_Tasman',
     'https://upload.wikimedia.org/wikipedia/commons/f/f8/AbelTasman.jpg',
     'Jacob Gerritsz. Cuyp, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:AbelTasman.jpg'),

    ('cook-botany-bay', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'James Cook lands at Botany Bay', 'James Cook débarque à Botany Bay',
     'On 29 April 1770, Captain James Cook and the crew of the Endeavour landed at Botany Bay on Australia''s east coast. The bay was named after the many unknown plants the naturalists collected there.',
     'Le 29 avril 1770, le capitaine James Cook et l''équipage de l''Endeavour débarquent à Botany Bay, sur la côte est de l''Australie. La baie doit son nom aux nombreuses plantes inconnues qu''y récoltent les naturalistes.',
     '29 April 1770', '29 avril 1770', 1770, 4, 29, 'oceania', 'Océanie', ARRAY['AU'], 'easy',
     ARRAY['exploration', 'australia'], ARRAY['exploration', 'australie'], 10,
     'https://fr.wikipedia.org/wiki/Botany_Bay',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Sydney_from_Botany_Bay_looking_north_%28aerial%29.jpg/1280px-Sydney_from_Botany_Bay_looking_north_%28aerial%29.jpg',
     'Tim Starling, CC BY 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Sydney_from_Botany_Bay_looking_north_(aerial).jpg'),

    ('mort-cook', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The death of James Cook in Hawaii', 'La mort de James Cook à Hawaï',
     'On 14 February 1779, Captain James Cook was killed at Kealakekua Bay in Hawaii during a clash with the islanders. He had explored the Pacific more than anyone before him.',
     'Le 14 février 1779, le capitaine James Cook est tué dans la baie de Kealakekua, à Hawaï, lors d''un affrontement avec les habitants. Il avait exploré le Pacifique plus que quiconque avant lui.',
     '14 February 1779', '14 février 1779', 1779, 2, 14, 'oceania', 'Océanie', ARRAY['US'], 'medium',
     ARRAY['exploration', 'hawaii'], ARRAY['exploration', 'hawaï'], 15,
     'https://fr.wikipedia.org/wiki/James_Cook',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Captainjamescookportrait.jpg/1280px-Captainjamescookportrait.jpg',
     'Nathaniel Dance-Holland, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Captainjamescookportrait.jpg'),

    ('first-fleet', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The First Fleet founds Sydney', 'La Première Flotte fonde Sydney',
     'On 26 January 1788, eleven British ships carrying more than 700 convicts settled at Sydney Cove. The date became Australia Day, which many Aboriginal people call Invasion Day.',
     'Le 26 janvier 1788, onze navires britanniques chargés de plus de 700 forçats s''installent à Sydney Cove. Cette date est devenue la fête nationale australienne, que beaucoup d''Aborigènes appellent « jour de l''invasion ».',
     '26 January 1788', '26 janvier 1788', 1788, 1, 26, 'oceania', 'Océanie', ARRAY['AU'], 'easy',
     ARRAY['colonisation', 'australia'], ARRAY['colonisation', 'australie'], 10,
     'https://fr.wikipedia.org/wiki/First_Fleet',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/The_First_Fleet_entering_Port_Jackson%2C_January_26%2C_1788%2C_drawn_1888_A9333001h.jpg/1280px-The_First_Fleet_entering_Port_Jackson%2C_January_26%2C_1788%2C_drawn_1888_A9333001h.jpg',
     'E. Le Bihan, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:The_First_Fleet_entering_Port_Jackson,_January_26,_1788,_drawn_1888_A9333001h.jpg'),

    ('mutinerie-bounty', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The mutiny on the Bounty', 'La mutinerie du Bounty',
     'On 28 April 1789, in the Pacific, Fletcher Christian and sailors of the Bounty rose up against Captain Bligh. Cast adrift in a launch, Bligh sailed more than 6,000 km to Timor; the mutineers ended up hiding on Pitcairn Island.',
     'Le 28 avril 1789, dans le Pacifique, Fletcher Christian et des marins du Bounty se révoltent contre le capitaine Bligh. Abandonné sur une chaloupe, Bligh parcourt plus de 6 000 km jusqu''à Timor ; les mutins finissent cachés sur l''île de Pitcairn.',
     '28 April 1789', '28 avril 1789', 1789, 4, 28, 'oceania', 'Océanie', ARRAY['TO'], 'medium',
     ARRAY['navigation', 'revolt'], ARRAY['navigation', 'révolte'], 15,
     'https://fr.wikipedia.org/wiki/Mutinerie_du_Bounty',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Mutiny_HMS_Bounty.jpg/1280px-Mutiny_HMS_Bounty.jpg',
     'Robert Dodd, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Mutiny_HMS_Bounty.jpg'),

    ('traite-waitangi', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Treaty of Waitangi', 'Le traité de Waitangi',
     'On 6 February 1840, Māori chiefs and the British Crown signed the Treaty of Waitangi, New Zealand''s founding document. Its English and Māori versions do not say quite the same thing, which still fuels debate.',
     'Le 6 février 1840, des chefs maoris et la Couronne britannique signent le traité de Waitangi, acte fondateur de la Nouvelle-Zélande. Ses versions anglaise et maorie ne disent pas tout à fait la même chose, ce qui nourrit encore des débats.',
     '6 February 1840', '6 février 1840', 1840, 2, 6, 'oceania', 'Océanie', ARRAY['NZ'], 'easy',
     ARRAY['treaty', 'maori'], ARRAY['traité', 'maoris'], 10,
     'https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Waitangi',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Treatyofwaitangi.jpg/1280px-Treatyofwaitangi.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Treatyofwaitangi.jpg'),

    ('vote-femmes-nz', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'New Zealand women win the vote', 'Les Néo-Zélandaises obtiennent le droit de vote',
     'On 19 September 1893, New Zealand became the first self-governing country to give women the vote in national elections, after petitions led by Kate Sheppard.',
     'Le 19 septembre 1893, la Nouvelle-Zélande devient le premier pays autonome à accorder le droit de vote aux femmes aux élections nationales, après les pétitions menées par Kate Sheppard.',
     '19 September 1893', '19 septembre 1893', 1893, 9, 19, 'oceania', 'Océanie', ARRAY['NZ'], 'easy',
     ARRAY['women''s rights', 'politics'], ARRAY['droits des femmes', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/Kate_Sheppard',
     'https://upload.wikimedia.org/wikipedia/commons/6/60/Kate_Sheppard.jpg',
     'H. H. Clifford, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Kate_Sheppard.jpg'),

    ('federation-australie', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The birth of Australia', 'La naissance de l''Australie',
     'On 1 January 1901, six British colonies joined together to form the Commonwealth of Australia. Edmund Barton became the new country''s first prime minister.',
     'Le 1er janvier 1901, six colonies britanniques s''unissent pour former le Commonwealth d''Australie. Edmund Barton devient le premier Premier ministre du nouveau pays.',
     '1 January 1901', '1er janvier 1901', 1901, 1, 1, 'oceania', 'Océanie', ARRAY['AU'], 'easy',
     ARRAY['australia', 'politics'], ARRAY['australie', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/F%C3%A9d%C3%A9ration_de_l%27Australie',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Town_Hall%2C_Sydney%2C_Inauguration_of_Australian_Commonwealth.jpg/1280px-Town_Hall%2C_Sydney%2C_Inauguration_of_Australian_Commonwealth.jpg',
     'W. A. Gullick, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Town_Hall,_Sydney,_Inauguration_of_Australian_Commonwealth.jpg'),

    ('debarquement-gallipoli', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Anzac landing at Gallipoli', 'Le débarquement des Anzacs à Gallipoli',
     'On 25 April 1915, Australian and New Zealand soldiers landed at Gallipoli in Turkey. The campaign failed with heavy losses, but 25 April, Anzac Day, remains a major day of remembrance in both countries.',
     'Le 25 avril 1915, des soldats australiens et néo-zélandais débarquent à Gallipoli, en Turquie. La campagne échoue au prix de lourdes pertes, mais le 25 avril, l''Anzac Day, reste une journée de mémoire majeure dans les deux pays.',
     '25 April 1915', '25 avril 1915', 1915, 4, 25, 'oceania', 'Océanie', ARRAY['AU', 'NZ', 'TR'], 'medium',
     ARRAY['first world war', 'military'], ARRAY['première guerre mondiale', 'militaire'], 15,
     'https://fr.wikipedia.org/wiki/Bataille_des_Dardanelles',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Landing_of_Australian_troops_at_ANZAC_Cove%2C_25_April_1915_slnsw.jpg/1280px-Landing_of_Australian_troops_at_ANZAC_Cove%2C_25_April_1915_slnsw.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Landing_of_Australian_troops_at_ANZAC_Cove,_25_April_1915_slnsw.jpg'),

    ('opera-sydney', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The opening of the Sydney Opera House', 'L''inauguration de l''Opéra de Sydney',
     'On 20 October 1973, Queen Elizabeth II opened the Sydney Opera House, whose white sails were designed by the Danish architect Jørn Utzon. It has been a UNESCO World Heritage Site since 2007.',
     'Le 20 octobre 1973, la reine Élisabeth II inaugure l''Opéra de Sydney, dont les voiles blanches ont été imaginées par l''architecte danois Jørn Utzon. Il est inscrit au patrimoine mondial de l''UNESCO depuis 2007.',
     '20 October 1973', '20 octobre 1973', 1973, 10, 20, 'oceania', 'Océanie', ARRAY['AU'], 'easy',
     ARRAY['architecture', 'australia'], ARRAY['architecture', 'australie'], 10,
     'https://fr.wikipedia.org/wiki/Op%C3%A9ra_de_Sydney',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Sydney_Opera_House_from_Circular_Quay%2C_2023%2C_10.jpg/1280px-Sydney_Opera_House_from_Circular_Quay%2C_2023%2C_10.jpg',
     'Kgbo, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_from_Circular_Quay,_2023,_10.jpg'),

    ('cite-interdite', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'The Forbidden City is completed', 'L''achèvement de la Cité interdite',
     'In 1420 the Yongle Emperor completed the Forbidden City in Beijing, where he moved the Ming capital. The palace was home to 24 emperors for almost five centuries.',
     'En 1420, l''empereur Yongle achève la Cité interdite à Pékin, où il installe la capitale des Ming. Le palais servira de résidence à 24 empereurs pendant près de cinq siècles.',
     '1420', '1420', 1420, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'easy',
     ARRAY['china', 'architecture'], ARRAY['chine', 'architecture'], 10,
     'https://fr.wikipedia.org/wiki/Cit%C3%A9_interdite',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_%2820315852831%29-_cropped.jpg/1280px-%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_%2820315852831%29-_cropped.jpg',
     'Han Zheng, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_(20315852831)-_cropped.jpg'),

    ('hangeul', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'King Sejong creates the Korean alphabet', 'Le roi Sejong crée l''alphabet coréen',
     'In 1446 King Sejong the Great promulgated hangul, a simple alphabet designed so that all the people could learn to read. South Korea celebrates it every 9 October.',
     'En 1446, le roi Sejong le Grand promulgue le hangeul, un alphabet simple conçu pour que tout le peuple puisse apprendre à lire. La Corée du Sud le célèbre chaque 9 octobre.',
     '1446', '1446', 1446, NULL, NULL, 'asia', 'Asie', ARRAY['KR'], 'medium',
     ARRAY['korea', 'writing'], ARRAY['corée', 'écriture'], 15,
     'https://fr.wikipedia.org/wiki/Hangeul',
     'https://upload.wikimedia.org/wikipedia/commons/c/c9/Hunminjeongum.jpg',
     'Hunminjeongeum (1446), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Hunminjeongum.jpg'),

    ('vasco-gama-calicut', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Vasco da Gama reaches India', 'Vasco de Gama arrive en Inde',
     'On 20 May 1498, the Portuguese Vasco da Gama reached Calicut in India after sailing around Africa. He opened the first direct sea route between Europe and Asia.',
     'Le 20 mai 1498, le Portugais Vasco de Gama arrive à Calicut, en Inde, après avoir contourné l''Afrique. Il ouvre la première route maritime directe entre l''Europe et l''Asie.',
     '20 May 1498', '20 mai 1498', 1498, 5, 20, 'asia', 'Asie', ARRAY['IN', 'PT'], 'easy',
     ARRAY['exploration', 'trade'], ARRAY['exploration', 'commerce'], 10,
     'https://fr.wikipedia.org/wiki/Vasco_de_Gama',
     'https://upload.wikimedia.org/wikipedia/commons/8/8d/Vasco_da_Gama_-_1838.png',
     'António Manuel da Fonseca, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Vasco_da_Gama_-_1838.png'),

    ('bataille-panipat', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Babur founds the Mughal Empire', 'Babur fonde l''Empire moghol',
     'On 21 April 1526 at Panipat, Babur defeated Ibrahim Lodi, the Sultan of Delhi, thanks to his cannons. His victory founded the Mughal Empire, which dominated India for more than two centuries.',
     'Le 21 avril 1526, à Panipat, Babur bat le sultan de Delhi Ibrahim Lodi grâce à ses canons. Sa victoire fonde l''Empire moghol, qui dominera l''Inde pendant plus de deux siècles.',
     '21 April 1526', '21 avril 1526', 1526, 4, 21, 'asia', 'Asie', ARRAY['IN'], 'medium',
     ARRAY['india', 'military'], ARRAY['inde', 'militaire'], 15,
     'https://fr.wikipedia.org/wiki/Premi%C3%A8re_bataille_de_Panipat',
     'https://upload.wikimedia.org/wikipedia/commons/3/37/The_battle_of_Panipat_and_the_death_of_Sultan_Ibr%C4%81h%C4%ABm%2C_the_last_of_the_L%C5%8Dd%C4%AB_Sultans_of_Delhi.jpg',
     'Baburnama, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:The_battle_of_Panipat_and_the_death_of_Sultan_Ibr%C4%81h%C4%ABm,_the_last_of_the_L%C5%8Dd%C4%AB_Sultans_of_Delhi.jpg'),

    ('unification-japon', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Hideyoshi reunifies Japan', 'Hideyoshi réunifie le Japon',
     'In 1590, after taking Odawara Castle, Toyotomi Hideyoshi subdued the last rival lords and reunified Japan, which had been torn apart by more than a century of civil war.',
     'En 1590, après la prise du château d''Odawara, Toyotomi Hideyoshi soumet les derniers seigneurs rivaux et réunifie le Japon, déchiré par plus d''un siècle de guerres civiles.',
     '1590', '1590', 1590, NULL, NULL, 'asia', 'Asie', ARRAY['JP'], 'medium',
     ARRAY['japan', 'politics'], ARRAY['japon', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/Toyotomi_Hideyoshi',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Toyotomi_Hideyoshi_c1598_Kodai-ji_Temple.png/1280px-Toyotomi_Hideyoshi_c1598_Kodai-ji_Temple.png',
     'Kanō Mitsunobu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Toyotomi_Hideyoshi_c1598_Kodai-ji_Temple.png'),

    ('bataille-sekigahara', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Battle of Sekigahara', 'La bataille de Sekigahara',
     'On 21 October 1600, Tokugawa Ieyasu won the Battle of Sekigahara. Named shogun in 1603, he founded a regime that ruled Japan until 1868.',
     'Le 21 octobre 1600, Tokugawa Ieyasu remporte la bataille de Sekigahara. Devenu shogun en 1603, il fonde un régime qui gouvernera le Japon jusqu''en 1868.',
     '21 October 1600', '21 octobre 1600', 1600, 10, 21, 'asia', 'Asie', ARRAY['JP'], 'easy',
     ARRAY['japan', 'military'], ARRAY['japon', 'militaire'], 10,
     'https://fr.wikipedia.org/wiki/Bataille_de_Sekigahara',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Sekigaharascreen.jpg/1280px-Sekigaharascreen.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Sekigaharascreen.jpg'),

    ('fondation-voc', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Dutch East India Company', 'La Compagnie néerlandaise des Indes orientales',
     'On 20 March 1602 the Dutch East India Company (VOC) was founded. The first company to sell shares to the public, it controlled the spice trade from present-day Indonesia for two centuries.',
     'Le 20 mars 1602 naît la Compagnie néerlandaise des Indes orientales (VOC). Première société à vendre des actions au public, elle contrôlera pendant deux siècles le commerce des épices depuis l''actuelle Indonésie.',
     '20 March 1602', '20 mars 1602', 1602, 3, 20, 'asia', 'Asie', ARRAY['ID', 'NL'], 'medium',
     ARRAY['trade', 'colonisation'], ARRAY['commerce', 'colonisation'], 15,
     'https://fr.wikipedia.org/wiki/Compagnie_n%C3%A9erlandaise_des_Indes_orientales',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/VOC.svg/1280px-VOC.svg.png',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:VOC.svg'),

    ('taj-mahal', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The building of the Taj Mahal', 'La construction du Taj Mahal',
     'In 1632 the Mughal emperor Shah Jahan began building the Taj Mahal in Agra, a white marble mausoleum for his wife Mumtaz Mahal, who had died in childbirth the year before.',
     'En 1632, l''empereur moghol Shah Jahan lance à Agra la construction du Taj Mahal, mausolée de marbre blanc dédié à son épouse Mumtaz Mahal, morte en couches l''année précédente.',
     '1632', '1632', 1632, NULL, NULL, 'asia', 'Asie', ARRAY['IN'], 'easy',
     ARRAY['india', 'architecture'], ARRAY['inde', 'architecture'], 10,
     'https://fr.wikipedia.org/wiki/Taj_Mahal',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/1280px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg',
     'Yann Forget, King of Hearts, Jbarta, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Taj_Mahal,_Agra,_India_edit3.jpg'),

    ('sakoku', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Japan closes itself off', 'Le Japon se ferme au monde',
     'In 1639 the Tokugawa shogunate expelled the Portuguese and closed Japan to foreigners. Only the Dutch and the Chinese could still trade, at Nagasaki. The isolation lasted more than two centuries.',
     'En 1639, le shogunat Tokugawa expulse les Portugais et ferme le Japon aux étrangers. Seuls les Néerlandais et les Chinois peuvent encore commercer, à Nagasaki. Cet isolement durera plus de deux siècles.',
     '1639', '1639', 1639, NULL, NULL, 'asia', 'Asie', ARRAY['JP'], 'medium',
     ARRAY['japan', 'politics'], ARRAY['japon', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/Sakoku',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Plattegrond_van_Deshima.jpg/1280px-Plattegrond_van_Deshima.jpg',
     'Isaac Titsingh, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Plattegrond_van_Deshima.jpg'),

    ('qing-pekin', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Manchus take Beijing', 'Les Mandchous prennent Pékin',
     'In 1644 the Manchus seized Beijing and founded the Qing dynasty. It was China''s last imperial dynasty, until the Republic was proclaimed in 1912.',
     'En 1644, les Mandchous s''emparent de Pékin et fondent la dynastie Qing. Ce sera la dernière dynastie impériale de Chine, jusqu''à la proclamation de la République en 1912.',
     '1644', '1644', 1644, NULL, NULL, 'asia', 'Asie', ARRAY['CN'], 'medium',
     ARRAY['china', 'dynasty'], ARRAY['chine', 'dynastie'], 15,
     'https://fr.wikipedia.org/wiki/Dynastie_Qing',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Qing_dynasty_in_1760.svg/1280px-Qing_dynasty_in_1760.svg.png',
     'Aldermanseven, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Qing_dynasty_in_1760.svg'),

    ('traite-nankin', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Treaty of Nanking', 'Le traité de Nankin',
     'On 29 August 1842, the Treaty of Nanking ended the First Opium War. Defeated, China ceded Hong Kong to Britain and opened five ports to trade: the first of the "unequal treaties".',
     'Le 29 août 1842, le traité de Nankin met fin à la première guerre de l''opium. Vaincue, la Chine cède Hong Kong au Royaume-Uni et ouvre cinq ports au commerce : c''est le premier des « traités inégaux ».',
     '29 August 1842', '29 août 1842', 1842, 8, 29, 'asia', 'Asie', ARRAY['CN', 'GB'], 'medium',
     ARRAY['china', 'treaty'], ARRAY['chine', 'traité'], 15,
     'https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Nankin',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/The_Signing_of_the_Treaty_of_Nanking.jpg/1280px-The_Signing_of_the_Treaty_of_Nanking.jpg',
     'John Platt et John Burnet, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:The_Signing_of_the_Treaty_of_Nanking.jpg'),

    ('restauration-meiji', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Meiji Restoration', 'La restauration de Meiji',
     'On 3 January 1868, power was restored to Emperor Meiji, ending more than 250 years of shogunate rule. Within a few decades Japan modernised and became a major industrial power.',
     'Le 3 janvier 1868, le pouvoir est rendu à l''empereur Meiji, mettant fin à plus de 250 ans de shogunat. En quelques décennies, le Japon se modernise et devient une grande puissance industrielle.',
     '3 January 1868', '3 janvier 1868', 1868, 1, 3, 'asia', 'Asie', ARRAY['JP'], 'medium',
     ARRAY['japan', 'politics'], ARRAY['japon', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/Restauration_de_Meiji',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/MeijiJoukyou.jpg/1280px-MeijiJoukyou.jpg',
     'Alfred Roussin, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:MeijiJoukyou.jpg'),

    ('bombe-hiroshima', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The atomic bomb on Hiroshima', 'La bombe atomique sur Hiroshima',
     'On 6 August 1945 the United States dropped an atomic bomb on Hiroshima, then a second on Nagasaki three days later. More than 100,000 people died; Japan announced its surrender on 15 August.',
     'Le 6 août 1945, les États-Unis larguent une bombe atomique sur Hiroshima, puis une seconde sur Nagasaki trois jours plus tard. Plus de 100 000 personnes meurent ; le Japon annonce sa capitulation le 15 août.',
     '6 August 1945', '6 août 1945', 1945, 8, 6, 'asia', 'Asie', ARRAY['JP'], 'easy',
     ARRAY['second world war', 'nuclear'], ARRAY['seconde guerre mondiale', 'nucléaire'], 10,
     'https://fr.wikipedia.org/wiki/Bombardements_atomiques_d%27Hiroshima_et_de_Nagasaki',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Atomic_bombing_of_Japan.jpg/1280px-Atomic_bombing_of_Japan.jpg',
     'George R. Caron / Charles Levy, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Atomic_bombing_of_Japan.jpg'),

    ('independance-inde', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'Indian independence', 'L''indépendance de l''Inde',
     'On 15 August 1947 India became independent from Britain, with Nehru as prime minister. Partition from Pakistan, created the day before, drove more than ten million people from their homes.',
     'Le 15 août 1947, l''Inde devient indépendante du Royaume-Uni, avec Nehru pour Premier ministre. La partition avec le Pakistan, née la veille, provoque l''exode de plus de dix millions de personnes.',
     '15 August 1947', '15 août 1947', 1947, 8, 15, 'asia', 'Asie', ARRAY['IN', 'PK'], 'easy',
     ARRAY['india', 'decolonisation'], ARRAY['inde', 'décolonisation'], 10,
     'https://fr.wikipedia.org/wiki/Mouvement_pour_l%27ind%C3%A9pendance_de_l%27Inde',
     'https://upload.wikimedia.org/wikipedia/commons/4/4e/Jawaharlal_Nehru_gives_his_%22tryst_with_destiny%22_speech_at_Parliament_House_in_New_Delhi_in_1947_%2802%29.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Jawaharlal_Nehru_gives_his_%22tryst_with_destiny%22_speech_at_Parliament_House_in_New_Delhi_in_1947_(02).jpg'),

    ('proclamation-rpc', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'Mao proclaims the People''s Republic of China', 'Mao proclame la République populaire de Chine',
     'On 1 October 1949, Mao Zedong proclaimed the People''s Republic of China from Tiananmen Square. Defeated in the civil war, the Nationalists withdrew to the island of Taiwan.',
     'Le 1er octobre 1949, Mao Zedong proclame la République populaire de Chine depuis la place Tian''anmen. Vaincus dans la guerre civile, les nationalistes se replient sur l''île de Taïwan.',
     '1 October 1949', '1er octobre 1949', 1949, 10, 1, 'asia', 'Asie', ARRAY['CN'], 'easy',
     ARRAY['china', 'politics'], ARRAY['chine', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/Chine',
     'https://upload.wikimedia.org/wikipedia/commons/8/85/Mao_Proclaiming_New_China.JPG',
     'Orihara1, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Mao_Proclaiming_New_China.JPG'),

    ('bataille-tondibi', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The fall of the Songhai Empire', 'La chute de l''Empire songhaï',
     'In March 1591 at Tondibi, a Moroccan army armed with arquebuses crushed the troops of the Songhai Empire. One of the largest empires in African history collapsed.',
     'En mars 1591, à Tondibi, une armée marocaine équipée d''arquebuses écrase les troupes de l''Empire songhaï. L''un des plus vastes empires de l''histoire africaine s''effondre.',
     'March 1591', 'Mars 1591', 1591, 3, NULL, 'africa', 'Afrique', ARRAY['ML'], 'hard',
     ARRAY['military', 'empire'], ARRAY['militaire', 'empire'], 20,
     'https://fr.wikipedia.org/wiki/Bataille_de_Tondibi',
     'https://upload.wikimedia.org/wikipedia/commons/a/ab/Askia.jpg',
     'Taguelmoust, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Askia.jpg'),

    ('reine-nzinga', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Nzinga, a queen against the Portuguese', 'Nzinga, reine face aux Portugais',
     'Around 1624, Nzinga became queen of Ndongo, in present-day Angola. A diplomat and war leader, she resisted the Portuguese and the slave trade for almost forty years.',
     'Vers 1624, Nzinga devient reine du Ndongo, dans l''actuel Angola. Diplomate et cheffe de guerre, elle résiste pendant près de quarante ans aux Portugais et à la traite des esclaves.',
     'c. 1624', 'Vers 1624', 1624, NULL, NULL, 'africa', 'Afrique', ARRAY['AO'], 'medium',
     ARRAY['angola', 'resistance'], ARRAY['angola', 'résistance'], 15,
     'https://fr.wikipedia.org/wiki/Njinga_du_Ndongo_et_du_Matamba',
     'https://upload.wikimedia.org/wikipedia/commons/2/21/Ann_Zingha.jpg',
     'Achille Devéria, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ann_Zingha.jpg'),

    ('fondation-gondar', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Gondar, the city of castles', 'Gondar, capitale des châteaux',
     'In 1636 Emperor Fasilides made Gondar the capital of Ethiopia and built a castle there. His successors added palaces and churches, now a World Heritage Site.',
     'En 1636, l''empereur Fasilidas fait de Gondar la capitale de l''Éthiopie et y bâtit un château. Ses successeurs y ajoutent palais et églises, aujourd''hui inscrits au patrimoine mondial.',
     '1636', '1636', 1636, NULL, NULL, 'africa', 'Afrique', ARRAY['ET'], 'hard',
     ARRAY['ethiopia', 'architecture'], ARRAY['éthiopie', 'architecture'], 20,
     'https://fr.wikipedia.org/wiki/Gondar',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Gonder_from_the_Goha_hotel.jpg/1280px-Gonder_from_the_Goha_hotel.jpg',
     'Giustino, CC BY 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Gonder_from_the_Goha_hotel.jpg'),

    ('fondation-le-cap', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The founding of Cape Town', 'La fondation du Cap',
     'On 6 April 1652, Jan van Riebeeck set up a supply station at the Cape for Dutch ships bound for Asia. It marked the start of European colonisation in South Africa.',
     'Le 6 avril 1652, Jan van Riebeeck installe au Cap un poste de ravitaillement pour les navires néerlandais en route vers l''Asie. C''est le début de la colonisation européenne de l''Afrique du Sud.',
     '6 April 1652', '6 avril 1652', 1652, 4, 6, 'africa', 'Afrique', ARRAY['ZA'], 'medium',
     ARRAY['colonisation', 'south africa'], ARRAY['colonisation', 'afrique du sud'], 15,
     'https://fr.wikipedia.org/wiki/Jan_van_Riebeeck',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Portret_van_Jan_van_Riebeeck_%281619-77%29._Bevelhebber_van_Kaap_de_Goede_Hoop_en_van_Malacca_en_secretaris_van_de_Hoge_Regering_van_Batavia%2C_SK-A-805.jpg/1280px-Portret_van_Jan_van_Riebeeck_%281619-77%29._Bevelhebber_van_Kaap_de_Goede_Hoop_en_van_Malacca_en_secretaris_van_de_Hoge_Regering_van_Batavia%2C_SK-A-805.jpg',
     'Auteur inconnu, CC0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Portret_van_Jan_van_Riebeeck_(1619-77)._Bevelhebber_van_Kaap_de_Goede_Hoop_en_van_Malacca_en_secretaris_van_de_Hoge_Regering_van_Batavia,_SK-A-805.jpg'),

    ('empire-ashanti', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The birth of the Ashanti Empire', 'La naissance de l''Empire ashanti',
     'In 1701 Osei Tutu founded the Ashanti Empire in present-day Ghana. According to tradition, a Golden Stool that came down from the sky embodies the soul of the nation, which became a great trading power.',
     'En 1701, Osei Tutu fonde l''Empire ashanti, dans l''actuel Ghana. Selon la tradition, un Tabouret d''or descendu du ciel symbolise l''âme de la nation, qui deviendra une grande puissance commerciale.',
     '1701', '1701', 1701, NULL, NULL, 'africa', 'Afrique', ARRAY['GH'], 'medium',
     ARRAY['ghana', 'empire'], ARRAY['ghana', 'empire'], 15,
     'https://fr.wikipedia.org/wiki/Empire_ashanti',
     'https://upload.wikimedia.org/wikipedia/commons/a/a3/Golden_stool_31_January_1935.jpg',
     'Gouvernement britannique, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Golden_stool_31_January_1935.jpg'),

    ('canal-suez', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The opening of the Suez Canal', 'L''inauguration du canal de Suez',
     'On 17 November 1869 the Suez Canal was opened. Dug under Ferdinand de Lesseps, it links the Mediterranean to the Red Sea and spares ships the voyage around Africa.',
     'Le 17 novembre 1869, le canal de Suez est inauguré. Percé sous la direction de Ferdinand de Lesseps, il relie la Méditerranée à la mer Rouge et évite aux navires le tour de l''Afrique.',
     '17 November 1869', '17 novembre 1869', 1869, 11, 17, 'africa', 'Afrique', ARRAY['EG'], 'easy',
     ARRAY['egypt', 'trade'], ARRAY['égypte', 'commerce'], 10,
     'https://fr.wikipedia.org/wiki/Canal_de_Suez',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Iss016e019375.jpg/1280px-Iss016e019375.jpg',
     'NASA, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Iss016e019375.jpg'),

    ('bataille-adoua', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Ethiopian victory at Adwa', 'La victoire éthiopienne d''Adoua',
     'On 1 March 1896 the army of Emperor Menelik II crushed the Italian forces at Adwa. The victory preserved Ethiopia''s independence, making it one of the only African countries never colonised.',
     'Le 1er mars 1896, l''armée de l''empereur Ménélik II écrase les troupes italiennes à Adoua. Cette victoire préserve l''indépendance de l''Éthiopie, l''un des seuls pays d''Afrique jamais colonisés.',
     '1 March 1896', '1er mars 1896', 1896, 3, 1, 'africa', 'Afrique', ARRAY['ET'], 'medium',
     ARRAY['ethiopia', 'military'], ARRAY['éthiopie', 'militaire'], 15,
     'https://fr.wikipedia.org/wiki/Bataille_d%27Adoua',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Adoua_1.jpg/1280px-Adoua_1.jpg',
     'The Graphic, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Adoua_1.jpg'),

    ('independance-ghana', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'Ghana''s independence', 'L''indépendance du Ghana',
     'On 6 March 1957 the British Gold Coast became independent Ghana, led by Kwame Nkrumah. The first in West Africa, it paved the way for African independence.',
     'Le 6 mars 1957, la Côte-de-l''Or britannique devient le Ghana indépendant, sous la conduite de Kwame Nkrumah. Pionnière en Afrique de l''Ouest, elle ouvre la voie aux indépendances africaines.',
     '6 March 1957', '6 mars 1957', 1957, 3, 6, 'africa', 'Afrique', ARRAY['GH'], 'easy',
     ARRAY['decolonisation', 'ghana'], ARRAY['décolonisation', 'ghana'], 10,
     'https://fr.wikipedia.org/wiki/Kwame_Nkrumah',
     'https://upload.wikimedia.org/wikipedia/commons/5/5c/Kwame_Nkrumah_Portrait%2C_The_National_Archives_UK.jpg',
     'The National Archives UK, OGL v1.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Kwame_Nkrumah_Portrait,_The_National_Archives_UK.jpg'),

    ('liberation-mandela', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'Nelson Mandela is freed', 'La libération de Nelson Mandela',
     'On 11 February 1990 Nelson Mandela walked out of prison after 27 years behind bars. His release opened the negotiations that ended apartheid in South Africa.',
     'Le 11 février 1990, Nelson Mandela sort de prison après 27 ans de détention. Sa libération ouvre les négociations qui mettront fin à l''apartheid en Afrique du Sud.',
     '11 February 1990', '11 février 1990', 1990, 2, 11, 'africa', 'Afrique', ARRAY['ZA'], 'easy',
     ARRAY['apartheid', 'civil rights'], ARRAY['apartheid', 'droits civiques'], 10,
     'https://fr.wikipedia.org/wiki/Nelson_Mandela',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Nelson_Mandela_1994.jpg/1280px-Nelson_Mandela_1994.jpg',
     'Kingkongphoto, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Nelson_Mandela_1994.jpg'),

    ('elections-1994', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'South Africa''s first multiracial elections', 'Les premières élections multiraciales d''Afrique du Sud',
     'On 27 April 1994, South Africans of all races voted together for the first time. Nelson Mandela was elected president; the day is now celebrated as Freedom Day.',
     'Le 27 avril 1994, les Sud-Africains de toutes origines votent ensemble pour la première fois. Nelson Mandela est élu président ; ce jour est désormais la fête de la Liberté.',
     '27 April 1994', '27 avril 1994', 1994, 4, 27, 'africa', 'Afrique', ARRAY['ZA'], 'easy',
     ARRAY['apartheid', 'democracy'], ARRAY['apartheid', 'démocratie'], 10,
     'https://fr.wikipedia.org/wiki/%C3%89lections_g%C3%A9n%C3%A9rales_sud-africaines_de_1994',
     'https://upload.wikimedia.org/wikipedia/commons/7/73/Mandela_voting_in_1994.jpg',
     'Paul Weinberg, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Mandela_voting_in_1994.jpg'),

    ('ecriture-cuneiforme', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The invention of writing', 'L''invention de l''écriture',
     'Around 3300 BCE, in Sumer in Mesopotamia, scribes marked signs on clay tablets to keep accounts. This script, called cuneiform, marks the end of prehistory.',
     'Vers 3300 av. J.-C., à Sumer, en Mésopotamie, des scribes tracent des signes sur des tablettes d''argile pour tenir des comptes. Cette écriture, appelée cunéiforme, marque la fin de la Préhistoire.',
     'c. 3300 BCE', 'Vers 3300 av. J.-C.', -3300, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ'], 'easy',
     ARRAY['mesopotamia', 'writing'], ARRAY['mésopotamie', 'écriture'], 10,
     'https://fr.wikipedia.org/wiki/Cun%C3%A9iforme',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Clay_tablet%2C_late_Uruk_period%2C_3300-3100_BCE._Proto-cuneiform_signs%2C_food_issue_list_%22_rations%22_written_by_combining_a_human_head_and_a_bowl._Purchased_via_Christie%27s_in_1989%2C_with_contribution_from_the_British_Museum_Friends.jpg/1280px-thumbnail.jpg',
     'Osama Shukir Muhammed Amin, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Clay_tablet,_late_Uruk_period,_3300-3100_BCE._Proto-cuneiform_signs,_food_issue_list_%22_rations%22_written_by_combining_a_human_head_and_a_bowl._Purchased_via_Christie%27s_in_1989,_with_contribution_from_the_British_Museum_Friends.jpg'),

    ('code-hammurabi', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Code of Hammurabi', 'Le code de Hammurabi',
     'Around 1750 BCE, King Hammurabi of Babylon had nearly 300 laws carved on a basalt stele. The code, now in the Louvre, is one of the oldest known law texts.',
     'Vers 1750 av. J.-C., le roi de Babylone Hammurabi fait graver près de 300 lois sur une stèle de basalte. Ce code, aujourd''hui au Louvre, est l''un des plus anciens textes de lois connus.',
     'c. 1750 BCE', 'Vers 1750 av. J.-C.', -1750, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ'], 'medium',
     ARRAY['mesopotamia', 'law'], ARRAY['mésopotamie', 'droit'], 15,
     'https://fr.wikipedia.org/wiki/Code_de_Hammurabi',
     'https://upload.wikimedia.org/wikipedia/commons/6/64/P1050763_Louvre_code_Hammurabi_face_rwk.JPG',
     'Mbzt, CC BY 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:P1050763_Louvre_code_Hammurabi_face_rwk.JPG'),

    ('cyrus-babylone', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Cyrus the Great takes Babylon', 'Cyrus le Grand prend Babylone',
     'In 539 BCE the Persian king Cyrus II entered Babylon. He allowed deported peoples, including the Jews, to return home, and built the largest empire the world had yet seen.',
     'En 539 av. J.-C., le roi perse Cyrus II entre dans Babylone. Il autorise les peuples déportés, dont les Juifs, à rentrer chez eux, et bâtit le plus vaste empire que le monde ait connu.',
     '539 BCE', '539 av. J.-C.', -539, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IQ', 'IR'], 'medium',
     ARRAY['persia', 'empire'], ARRAY['perse', 'empire'], 15,
     'https://fr.wikipedia.org/wiki/Cyrus_le_Grand',
     'https://upload.wikimedia.org/wikipedia/commons/5/57/Cyrus_II_%28The_Great%29_%28cropped%29.jpg',
     'Surenae, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Cyrus_II_(The_Great)_(cropped).jpg'),

    ('persepolis', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The founding of Persepolis', 'La fondation de Persépolis',
     'Around 518 BCE King Darius I founded Persepolis, the ceremonial capital of the Persian Empire. Its grand palaces were burned by Alexander the Great in 330 BCE.',
     'Vers 518 av. J.-C., le roi Darius Ier fonde Persépolis, capitale de cérémonie de l''Empire perse. Ses palais grandioses seront incendiés par Alexandre le Grand en 330 av. J.-C.',
     'c. 518 BCE', 'Vers 518 av. J.-C.', -518, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IR'], 'medium',
     ARRAY['persia', 'architecture'], ARRAY['perse', 'architecture'], 15,
     'https://fr.wikipedia.org/wiki/Pers%C3%A9polis',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/2018-09-21_Iran%2C_Persepolis%2C_Tachara_%28from_the_southeast%29.jpg/1280px-2018-09-21_Iran%2C_Persepolis%2C_Tachara_%28from_the_southeast%29.jpg',
     'Laurens R. Krol, CC BY 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:2018-09-21_Iran,_Persepolis,_Tachara_(from_the_southeast).jpg'),

    ('soliman-magnifique', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Suleiman the Magnificent becomes sultan', 'Soliman le Magnifique devient sultan',
     'In 1520 Suleiman became sultan of the Ottoman Empire. During his 46-year reign the empire reached its peak, stretching from the gates of Vienna to the Persian Gulf.',
     'En 1520, Soliman devient sultan de l''Empire ottoman. Pendant ses 46 ans de règne, l''empire atteint son apogée, des portes de Vienne jusqu''au golfe Persique.',
     '1520', '1520', 1520, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'easy',
     ARRAY['ottoman empire', 'politics'], ARRAY['empire ottoman', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/Soliman_le_Magnifique',
     'https://upload.wikimedia.org/wikipedia/commons/f/f7/Suleyman_%28enthroned%2C_receiving_Barbarossa_in_1533%29._S%C3%BCleymanname_%281558%29.jpg',
     'Süleymanname (1558), domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Suleyman_(enthroned,_receiving_Barbarossa_in_1533)._S%C3%BCleymanname_(1558).jpg'),

    ('ispahan-capitale', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Isfahan, "half the world"', 'Ispahan, « la moitié du monde »',
     'In 1598 Shah Abbas I made Isfahan the capital of Safavid Persia. He adorned it with a vast square and mosques so splendid that people said "Isfahan is half the world".',
     'En 1598, le shah Abbas Ier fait d''Ispahan la capitale de la Perse séfévide. Il l''embellit d''une immense place et de mosquées si splendides qu''on dira « Ispahan, c''est la moitié du monde ».',
     '1598', '1598', 1598, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IR'], 'medium',
     ARRAY['persia', 'architecture'], ARRAY['perse', 'architecture'], 15,
     'https://fr.wikipedia.org/wiki/Abbas_Ier_le_Grand',
     'https://upload.wikimedia.org/wikipedia/commons/2/2e/ShahAbbasPortraitFromItalianPainter.jpg',
     'Peintre italien anonyme, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:ShahAbbasPortraitFromItalianPainter.jpg'),

    ('mosquee-bleue', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Blue Mosque is completed', 'L''achèvement de la Mosquée bleue',
     'In 1616 the mosque of Sultan Ahmed I was completed in Istanbul. With its six minarets and thousands of blue tiles, it is known as the Blue Mosque.',
     'En 1616 s''achève à Istanbul la mosquée du sultan Ahmet Ier. Avec ses six minarets et ses milliers de carreaux de faïence bleue, elle est surnommée la Mosquée bleue.',
     '1616', '1616', 1616, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'easy',
     ARRAY['ottoman empire', 'architecture'], ARRAY['empire ottoman', 'architecture'], 10,
     'https://fr.wikipedia.org/wiki/Mosqu%C3%A9e_bleue',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Istanbul_%2834223582516%29_%28cropped%29.jpg/1280px-Istanbul_%2834223582516%29_%28cropped%29.jpg',
     'Pedro Szekely, CC BY-SA 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Istanbul_(34223582516)_(cropped).jpg'),

    ('nader-shah-delhi', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'Nader Shah sacks Delhi', 'Nader Shah pille Delhi',
     'In 1739 the Persian ruler Nader Shah crushed the Mughal army and sacked Delhi. He left with enormous loot, including the Peacock Throne and the Koh-i-Noor diamond.',
     'En 1739, le souverain perse Nader Shah écrase l''armée moghole et met Delhi à sac. Il repart avec un butin colossal, dont le Trône du paon et le diamant Koh-i-Noor.',
     '1739', '1739', 1739, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['IR', 'IN'], 'hard',
     ARRAY['persia', 'military'], ARRAY['perse', 'militaire'], 20,
     'https://fr.wikipedia.org/wiki/Nader_Chah',
     'https://upload.wikimedia.org/wikipedia/commons/d/d8/NaderShahPainting.png',
     'Abolhassan Mostofi Ghaffari, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:NaderShahPainting.png'),

    ('pacte-diriyah', (SELECT id FROM public.historical_periods WHERE name = 'Époque moderne'),
     'The Pact of Diriyah', 'Le pacte de Diriyah',
     'In 1744, at Diriyah, Emir Muhammad bin Saud allied with the preacher Muhammad ibn Abd al-Wahhab. The pact drove the rise of the first Saudi state, forerunner of today''s Saudi Arabia.',
     'En 1744, à Diriyah, l''émir Mohammed ben Saoud s''allie au prédicateur Mohammed ben Abdelwahhab. Ce pacte assure l''essor du premier État saoudien, ancêtre de l''Arabie saoudite actuelle.',
     '1744', '1744', 1744, NULL, NULL, 'middle-east', 'Moyen-Orient', ARRAY['SA'], 'hard',
     ARRAY['arabia', 'religion'], ARRAY['arabie', 'religion'], 20,
     'https://fr.wikipedia.org/wiki/%C3%89mirat_de_Dariya',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/The_First_Saudi_State_Greatest_Extent.png/1280px-The_First_Saudi_State_Greatest_Extent.png',
     'AbdurRahman AbdulMoneim, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:The_First_Saudi_State_Greatest_Extent.png'),

    ('republique-turquie', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The proclamation of the Republic of Turkey', 'La proclamation de la République de Turquie',
     'On 29 October 1923, Mustafa Kemal proclaimed the Republic of Turkey on the ruins of the Ottoman Empire. As first president, he launched sweeping reforms: the Latin alphabet, secularism, votes for women.',
     'Le 29 octobre 1923, Mustafa Kemal proclame la République de Turquie sur les ruines de l''Empire ottoman. Premier président, il lance de profondes réformes : alphabet latin, laïcité, vote des femmes.',
     '29 October 1923', '29 octobre 1923', 1923, 10, 29, 'middle-east', 'Moyen-Orient', ARRAY['TR'], 'easy',
     ARRAY['turkey', 'politics'], ARRAY['turquie', 'politique'], 10,
     'https://fr.wikipedia.org/wiki/Mustafa_Kemal_Atat%C3%BCrk',
     'https://upload.wikimedia.org/wikipedia/commons/a/a8/Ataturk1930s.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Ataturk1930s.jpg'),

    ('petrole-arabie', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'Oil gushes in Saudi Arabia', 'Le pétrole jaillit en Arabie saoudite',
     'In March 1938, after years of fruitless drilling, the Dammam No. 7 well finally struck oil in large quantities. Saudi Arabia went on to become one of the world''s leading producers.',
     'En mars 1938, après des années de forages infructueux, le puits Dammam n° 7 découvre enfin du pétrole en grande quantité. L''Arabie saoudite deviendra l''un des premiers producteurs mondiaux.',
     'March 1938', 'Mars 1938', 1938, 3, NULL, 'middle-east', 'Moyen-Orient', ARRAY['SA'], 'medium',
     ARRAY['oil', 'economy'], ARRAY['pétrole', 'économie'], 15,
     'https://fr.wikipedia.org/wiki/Saudi_Aramco',
     'https://upload.wikimedia.org/wikipedia/commons/c/c4/Dammam_No._7_on_March_4%2C_1938.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Dammam_No._7_on_March_4,_1938.jpg'),

    ('creation-israel', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The creation of the State of Israel', 'La création de l''État d''Israël',
     'On 14 May 1948, David Ben-Gurion proclaimed the State of Israel. The first Arab-Israeli war broke out the next day, during which some 700,000 Palestinians fled or were driven from their land.',
     'Le 14 mai 1948, David Ben Gourion proclame l''État d''Israël. Dès le lendemain éclate la première guerre israélo-arabe, au cours de laquelle environ 700 000 Palestiniens fuient ou sont chassés de leurs terres.',
     '14 May 1948', '14 mai 1948', 1948, 5, 14, 'middle-east', 'Moyen-Orient', ARRAY['IL', 'PS'], 'medium',
     ARRAY['near east', 'politics'], ARRAY['proche-orient', 'politique'], 15,
     'https://fr.wikipedia.org/wiki/D%C3%A9claration_d%27ind%C3%A9pendance_de_l%27%C3%89tat_d%27Isra%C3%ABl',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Declaration_of_State_of_Israel_1948.jpg/1280px-Declaration_of_State_of_Israel_1948.jpg',
     'Rudi Weissenstein, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Declaration_of_State_of_Israel_1948.jpg'),

    ('revolution-iranienne', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The Iranian Revolution', 'La révolution iranienne',
     'On 11 February 1979 the Shah''s monarchy collapsed in Iran after months of protests. Ayatollah Khomeini, back from exile, established an Islamic Republic.',
     'Le 11 février 1979, la monarchie du shah s''effondre en Iran après des mois de manifestations. L''ayatollah Khomeini, rentré d''exil, instaure une République islamique.',
     '11 February 1979', '11 février 1979', 1979, 2, 11, 'middle-east', 'Moyen-Orient', ARRAY['IR'], 'easy',
     ARRAY['iran', 'revolution'], ARRAY['iran', 'révolution'], 10,
     'https://fr.wikipedia.org/wiki/R%C3%A9volution_iranienne',
     'https://upload.wikimedia.org/wikipedia/commons/a/a2/%D8%A7%D8%B9%D8%AA%D8%B1%D8%A7%D8%B6_%D9%85%D8%B1%D8%AF%D9%85_%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8%DB%8C.JPG',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:%D8%A7%D8%B9%D8%AA%D8%B1%D8%A7%D8%B6_%D9%85%D8%B1%D8%AF%D9%85_%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8%DB%8C.JPG'),

    ('burj-khalifa', (SELECT id FROM public.historical_periods WHERE name = 'Époque contemporaine'),
     'The opening of the Burj Khalifa', 'L''inauguration de la Burj Khalifa',
     'On 4 January 2010 the Burj Khalifa opened in Dubai. At 828 metres, it is the tallest structure ever built.',
     'Le 4 janvier 2010, la Burj Khalifa est inaugurée à Dubaï. Haute de 828 mètres, elle est la plus haute construction humaine du monde.',
     '4 January 2010', '4 janvier 2010', 2010, 1, 4, 'middle-east', 'Moyen-Orient', ARRAY['AE'], 'easy',
     ARRAY['architecture', 'record'], ARRAY['architecture', 'record'], 10,
     'https://fr.wikipedia.org/wiki/Burj_Khalifa',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Vue_du_haut_Burj.jpg/1280px-Vue_du_haut_Burj.jpg',
     'Mguil13, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Vue_du_haut_Burj.jpg'),

    ('caral', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Caral, the oldest city in the Americas', 'Caral, la plus vieille ville des Amériques',
     'Around 2600 BCE, Caral rose in Peru, with its pyramids and plazas. Contemporary with the pyramids of Egypt, it is the oldest known city in the Americas.',
     'Vers 2600 av. J.-C., au Pérou, s''élève Caral, avec ses pyramides et ses places. Contemporaine des pyramides d''Égypte, c''est la plus ancienne ville connue du continent américain.',
     'c. 2600 BCE', 'Vers 2600 av. J.-C.', -2600, NULL, NULL, 'americas', 'Amériques', ARRAY['PE'], 'hard',
     ARRAY['peru', 'city'], ARRAY['pérou', 'ville'], 20,
     'https://fr.wikipedia.org/wiki/Caral',
     'https://upload.wikimedia.org/wikipedia/commons/1/1d/PiramidesdeCaral.JPG',
     'Percy Meza, CC BY 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:PiramidesdeCaral.JPG'),

    ('tetes-olmeques', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Olmec colossal heads', 'Les têtes colossales olmèques',
     'Before 900 BCE the Olmecs, one of Mexico''s first civilisations, carved huge basalt heads weighing up to several tens of tonnes. Seventeen are known today.',
     'Avant 900 av. J.-C., les Olmèques, l''une des premières civilisations du Mexique, sculptent d''énormes têtes de basalte pesant jusqu''à plusieurs dizaines de tonnes. On en connaît aujourd''hui dix-sept.',
     'Before 900 BCE', 'Avant 900 av. J.-C.', -900, NULL, NULL, 'americas', 'Amériques', ARRAY['MX'], 'medium',
     ARRAY['mexico', 'art'], ARRAY['mexique', 'art'], 15,
     'https://fr.wikipedia.org/wiki/T%C3%AAte_colossale_olm%C3%A8que',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Olmeca_head_in_Villahermosa.jpg/1280px-Olmeca_head_in_Villahermosa.jpg',
     'Glysiak, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Olmeca_head_in_Villahermosa.jpg'),

    ('lignes-nazca', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'The Nazca Lines', 'Les lignes de Nazca',
     'Between 500 BCE and 500 CE, the Nazca people traced huge figures (a hummingbird, a monkey, a spider) in the Peruvian desert that can only be seen whole from the sky.',
     'Entre 500 av. J.-C. et 500 apr. J.-C., le peuple Nazca trace dans le désert péruvien d''immenses figures (colibri, singe, araignée) visibles en entier seulement depuis le ciel.',
     'Between 500 BCE and 500 CE', 'Entre 500 av. J.-C. et 500 apr. J.-C.', -100, NULL, NULL, 'americas', 'Amériques', ARRAY['PE'], 'easy',
     ARRAY['peru', 'mystery'], ARRAY['pérou', 'mystère'], 10,
     'https://fr.wikipedia.org/wiki/G%C3%A9oglyphes_de_Nazca',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/L%C3%ADneas_de_Nazca%2C_Nazca%2C_Per%C3%BA%2C_2015-07-29%2C_DD_49.JPG/1280px-L%C3%ADneas_de_Nazca%2C_Nazca%2C_Per%C3%BA%2C_2015-07-29%2C_DD_49.JPG',
     'Diego Delso, CC BY-SA 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:L%C3%ADneas_de_Nazca,_Nazca,_Per%C3%BA,_2015-07-29,_DD_49.JPG'),

    ('teotihuacan', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Teotihuacan, the city of the gods', 'Teotihuacan, la cité des dieux',
     'Around 200 CE, Teotihuacan in Mexico completed its Pyramid of the Sun, one of the largest in the Americas. The city then had more than 100,000 inhabitants, among the most populous in the world.',
     'Vers l''an 200, Teotihuacan, au Mexique, achève sa pyramide du Soleil, l''une des plus grandes d''Amérique. La ville compte alors plus de 100 000 habitants, parmi les plus peuplées du monde.',
     'c. 200 CE', 'Vers 200 apr. J.-C.', 200, NULL, NULL, 'americas', 'Amériques', ARRAY['MX'], 'easy',
     ARRAY['mexico', 'city'], ARRAY['mexique', 'ville'], 10,
     'https://fr.wikipedia.org/wiki/Teotihuacan',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/View_from_Pyramide_de_la_luna.jpg/1280px-View_from_Pyramide_de_la_luna.jpg',
     'Jackhynes, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:View_from_Pyramide_de_la_luna.jpg'),

    ('tikal', (SELECT id FROM public.historical_periods WHERE name = 'Antiquité'),
     'Tikal and the golden age of the Maya', 'Tikal et l''âge d''or des Mayas',
     'Around 250 CE the Maya Classic period began. In the heart of the Guatemalan jungle, Tikal became one of the most powerful cities, with temple-pyramids more than 60 metres high.',
     'Vers 250 commence la période classique maya. Au cœur de la jungle du Guatemala, Tikal devient l''une des cités les plus puissantes, avec des temples-pyramides de plus de 60 mètres.',
     'c. 250 CE', 'Vers 250 apr. J.-C.', 250, NULL, NULL, 'americas', 'Amériques', ARRAY['GT'], 'medium',
     ARRAY['maya', 'city'], ARRAY['mayas', 'ville'], 15,
     'https://fr.wikipedia.org/wiki/Tikal',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Tikal_Temple1_2006_08_11.JPG/1280px-Tikal_Temple1_2006_08_11.JPG',
     'Raymond Ostertag, CC BY-SA 2.5, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Tikal_Temple1_2006_08_11.JPG'),

    ('vikings-amerique', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The Vikings in America', 'Les Vikings en Amérique',
     'In 1021, Vikings felled trees at L''Anse aux Meadows in Newfoundland, as a study of the wood proved in 2021. Almost 500 years before Columbus, Europeans had already set foot in America.',
     'En 1021, des Vikings abattent des arbres à L''Anse aux Meadows, à Terre-Neuve : une étude du bois l''a démontré en 2021. Près de 500 ans avant Colomb, des Européens avaient déjà posé le pied en Amérique.',
     '1021', '1021', 1021, NULL, NULL, 'americas', 'Amériques', ARRAY['CA'], 'medium',
     ARRAY['vikings', 'exploration'], ARRAY['vikings', 'exploration'], 15,
     'https://fr.wikipedia.org/wiki/L%27Anse_aux_Meadows',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Authentic_Viking_recreation.jpg/1280px-Authentic_Viking_recreation.jpg',
     'Dylan Kereluk, CC BY 2.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Authentic_Viking_recreation.jpg'),

    ('chichen-itza', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The pyramid of Chichén Itzá', 'La pyramide de Chichén Itzá',
     'Around the year 1000, the Maya of Chichén Itzá built the pyramid of Kukulcán. At the equinoxes, the shadow of its steps forms a serpent that seems to slither down the staircase.',
     'Vers l''an 1000, les Mayas de Chichén Itzá bâtissent la pyramide de Kukulcán. Aux équinoxes, l''ombre de ses marches dessine un serpent qui semble descendre le long de l''escalier.',
     'c. 1000', 'Vers l''an 1000', 1000, NULL, NULL, 'americas', 'Amériques', ARRAY['MX'], 'easy',
     ARRAY['maya', 'architecture'], ARRAY['mayas', 'architecture'], 10,
     'https://fr.wikipedia.org/wiki/Chich%C3%A9n_Itz%C3%A1',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/El_Castillo_Stitch_2008_Edit_1.jpg/1280px-El_Castillo_Stitch_2008_Edit_1.jpg',
     'Fcb981, CC BY-SA 3.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:El_Castillo_Stitch_2008_Edit_1.jpg'),

    ('cahokia', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Cahokia, the great city of the Mississippi', 'Cahokia, la grande cité du Mississippi',
     'In the 12th century Cahokia, near present-day St. Louis, was the largest city in North America north of Mexico. It had about 15,000 inhabitants and an earthen mound 30 metres high.',
     'Au XIIe siècle, Cahokia, près de l''actuelle Saint-Louis, est la plus grande ville d''Amérique du Nord au nord du Mexique. Elle compte environ 15 000 habitants et un tertre de terre de 30 mètres de haut.',
     '12th century', 'XIIe siècle', 1100, NULL, NULL, 'americas', 'Amériques', ARRAY['US'], 'hard',
     ARRAY['native americans', 'city'], ARRAY['amérindiens', 'ville'], 20,
     'https://fr.wikipedia.org/wiki/Cahokia',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Monks_Mound_-_Summer_2024.jpg/1280px-Monks_Mound_-_Summer_2024.jpg',
     'Skubasteve834, CC BY 4.0, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Monks_Mound_-_Summer_2024.jpg'),

    ('fondation-tenochtitlan', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'The founding of Tenochtitlan', 'La fondation de Tenochtitlan',
     'In 1325, according to tradition, the Aztecs founded Tenochtitlan on an island in Lake Texcoco, where an eagle sat on a cactus. The city became Mexico City, and the eagle now appears on the Mexican flag.',
     'En 1325, selon la tradition, les Aztèques fondent Tenochtitlan sur une île du lac Texcoco, là où un aigle était posé sur un cactus. La ville deviendra Mexico, et l''aigle orne aujourd''hui le drapeau mexicain.',
     '1325', '1325', 1325, NULL, NULL, 'americas', 'Amériques', ARRAY['MX'], 'easy',
     ARRAY['aztecs', 'city'], ARRAY['aztèques', 'ville'], 10,
     'https://fr.wikipedia.org/wiki/Mexico-Tenochtitlan',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Tenochtitlan_Glyph_ZP.svg/1280px-Tenochtitlan_Glyph_ZP.svg.png',
     'XcepticZP, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Tenochtitlan_Glyph_ZP.svg'),

    ('pachacutec', (SELECT id FROM public.historical_periods WHERE name = 'Moyen Âge'),
     'Pachacuti builds the Inca Empire', 'Pachacutec bâtit l''Empire inca',
     'In 1438 Pachacuti became ruler of the Incas. Within a few decades he turned the small kingdom of Cusco into a vast empire that would stretch along the Andes.',
     'En 1438, Pachacutec prend la tête des Incas. En quelques décennies, il transforme le petit royaume de Cuzco en un immense empire qui s''étendra le long des Andes.',
     '1438', '1438', 1438, NULL, NULL, 'americas', 'Amériques', ARRAY['PE'], 'medium',
     ARRAY['incas', 'empire'], ARRAY['incas', 'empire'], 15,
     'https://fr.wikipedia.org/wiki/Pachacutec',
     'https://upload.wikimedia.org/wikipedia/commons/0/0f/PachacutecIXinca.jpg',
     'École de Cuzco, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:PachacutecIXinca.jpg'),

    ('traite-tordesillas', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'The Treaty of Tordesillas', 'Le traité de Tordesillas',
     'On 7 June 1494, Spain and Portugal divided the yet-to-be-discovered world along a line drawn through the Atlantic. That is why Portuguese is spoken in Brazil and Spanish in most of South America.',
     'Le 7 juin 1494, l''Espagne et le Portugal se partagent le monde à découvrir selon une ligne tracée dans l''Atlantique. C''est pourquoi on parle aujourd''hui portugais au Brésil et espagnol dans le reste de l''Amérique du Sud.',
     '7 June 1494', '7 juin 1494', 1494, 6, 7, 'americas', 'Amériques', ARRAY['BR'], 'medium',
     ARRAY['treaty', 'colonisation'], ARRAY['traité', 'colonisation'], 15,
     'https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Tordesillas',
     'https://upload.wikimedia.org/wikipedia/commons/b/bc/Treaty_of_Tordesillas.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Treaty_of_Tordesillas.jpg'),

    ('cabral-bresil', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Cabral reaches Brazil', 'Cabral atteint le Brésil',
     'On 22 April 1500, the Portuguese fleet of Pedro Álvares Cabral, bound for India, sighted the coast of Brazil. Portugal immediately claimed it.',
     'Le 22 avril 1500, la flotte portugaise de Pedro Álvares Cabral, en route vers l''Inde, aperçoit les côtes du Brésil. Le Portugal en revendique aussitôt la possession.',
     '22 April 1500', '22 avril 1500', 1500, 4, 22, 'americas', 'Amériques', ARRAY['BR'], 'easy',
     ARRAY['exploration', 'brazil'], ARRAY['exploration', 'brésil'], 10,
     'https://fr.wikipedia.org/wiki/Pedro_%C3%81lvares_Cabral',
     'https://upload.wikimedia.org/wikipedia/commons/2/24/Pedro_%C3%81lvares_Cabral_-_steel_engraving_by_American_Bank_Note_Company.jpg',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Pedro_%C3%81lvares_Cabral_-_steel_engraving_by_American_Bank_Note_Company.jpg'),

    ('capture-atahualpa', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'Pizarro captures the Inca emperor', 'Pizarro capture l''empereur inca',
     'On 16 November 1532 at Cajamarca, Francisco Pizarro and fewer than 200 Spaniards captured the Inca emperor Atahualpa. Despite a ransom of a room filled with gold, he was executed the following year.',
     'Le 16 novembre 1532, à Cajamarca, Francisco Pizarro et moins de 200 Espagnols capturent l''empereur inca Atahualpa. Malgré une rançon d''une pièce remplie d''or, il sera exécuté l''année suivante.',
     '16 November 1532', '16 novembre 1532', 1532, 11, 16, 'americas', 'Amériques', ARRAY['PE'], 'medium',
     ARRAY['incas', 'conquest'], ARRAY['incas', 'conquête'], 15,
     'https://fr.wikipedia.org/wiki/Atahualpa',
     'https://upload.wikimedia.org/wikipedia/commons/f/f2/Atahualpa_Inca_XIV.png',
     'Auteur inconnu, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Atahualpa_Inca_XIV.png'),

    ('argent-potosi', (SELECT id FROM public.historical_periods WHERE name = 'Renaissance'),
     'The silver mountain of Potosí', 'La montagne d''argent de Potosí',
     'In 1545 huge silver veins were discovered at Cerro Rico, in present-day Bolivia. Potosí became one of the largest cities in the world, at the cost of the forced labour of thousands of Indigenous people.',
     'En 1545, d''immenses filons d''argent sont découverts au Cerro Rico, dans l''actuelle Bolivie. Potosí devient l''une des plus grandes villes du monde, au prix du travail forcé de milliers d''Amérindiens.',
     '1545', '1545', 1545, NULL, NULL, 'americas', 'Amériques', ARRAY['BO'], 'medium',
     ARRAY['bolivia', 'economy'], ARRAY['bolivie', 'économie'], 15,
     'https://fr.wikipedia.org/wiki/Cerro_Rico',
     'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Cerro_ricco.jpg/1280px-Cerro_ricco.jpg',
     'Mhwater, domaine public, via Wikimedia Commons',
     'https://commons.wikimedia.org/wiki/File:Cerro_ricco.jpg')
  ON CONFLICT (slug) DO UPDATE SET
    period_id = EXCLUDED.period_id,
    title = EXCLUDED.title,
    title_fr = EXCLUDED.title_fr,
    description = EXCLUDED.description,
    description_fr = EXCLUDED.description_fr,
    date_text = EXCLUDED.date_text,
    date_text_fr = EXCLUDED.date_text_fr,
    year = EXCLUDED.year,
    month = EXCLUDED.month,
    day = EXCLUDED.day,
    region = EXCLUDED.region,
    region_fr = EXCLUDED.region_fr,
    countries = EXCLUDED.countries,
    difficulty = EXCLUDED.difficulty,
    tags = EXCLUDED.tags,
    tags_fr = EXCLUDED.tags_fr,
    points_reward = EXCLUDED.points_reward,
    source_url = EXCLUDED.source_url,
    image_url = EXCLUDED.image_url,
    image_credit = EXCLUDED.image_credit,
    image_source_url = EXCLUDED.image_source_url;
END
$$;
