import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { factId, title, description, region } = await req.json();

    if (!factId || !title || !description) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: factId, title, description' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }

    // Create a detailed prompt for the image generation
    const prompt = `Generate a historically accurate, educational illustration for: "${title}". 
Context: ${description}
Style: Historical, educational, realistic, appropriate for a learning app. 
Focus on the key elements that represent this historical fact.
Region: ${region || 'historical context'}
Make it visually engaging and culturally accurate.`;

    console.log('Generating image with prompt:', prompt);

    // Call Lovable AI for image generation
    const lovableResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('LOVABLE_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        modalities: ['image', 'text']
      })
    });

    if (!lovableResponse.ok) {
      throw new Error(`Lovable API error: ${lovableResponse.status}`);
    }

    const lovableData = await lovableResponse.json();
    const generatedImageUrl = lovableData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImageUrl) {
      throw new Error('No image generated by AI');
    }

    console.log('Image generated successfully');

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Convert base64 to blob
    const base64Data = generatedImageUrl.split(',')[1];
    const binaryData = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
    
    // Generate a unique filename
    const fileName = `fact-${factId}-${Date.now()}.png`;
    const filePath = `historical-facts/${fileName}`;

    // Upload to storage
    const { error: uploadError } = await supabase.storage
      .from('fact-images')
      .upload(filePath, binaryData, {
        contentType: 'image/png',
        upsert: true
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      // Return base64 as fallback
      return new Response(
        JSON.stringify({ 
          success: true, 
          imageUrl: generatedImageUrl,
          storage: 'base64',
          message: 'Image generated but not stored in bucket (using base64)'
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('fact-images')
      .getPublicUrl(filePath);

    // Update the fact with the new image URL
    const { error: updateError } = await supabase
      .from('historical_facts')
      .update({ image_url: publicUrl })
      .eq('id', factId);

    if (updateError) {
      console.error('Update error:', updateError);
      return new Response(
        JSON.stringify({ 
          success: true, 
          imageUrl: publicUrl,
          storage: 'uploaded',
          message: 'Image uploaded but not linked to fact (use URL manually)'
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        imageUrl: publicUrl,
        storage: 'uploaded',
        message: 'Image generated and linked successfully'
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error:', error);
    const message = error instanceof Error ? error.message : String(error);
    return new Response(
      JSON.stringify({ 
        error: 'Failed to generate image', 
        details: message 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
